.SPASample {
  /*!
 * Bootstrap v3.3.4 (http://getbootstrap.com)
 * Copyright 2011-2015 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */
  /*! normalize.css v3.0.2 | MIT License | git.io/normalize */
  /*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
  /*# sourceMappingURL=bootstrap.css.map */
}
.SPASample html {
  font-family: sans-serif;
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
}
.SPASample body {
  margin: 0;
}
.SPASample article,
.SPASample aside,
.SPASample details,
.SPASample figcaption,
.SPASample figure,
.SPASample footer,
.SPASample header,
.SPASample hgroup,
.SPASample main,
.SPASample menu,
.SPASample nav,
.SPASample section,
.SPASample summary {
  display: block;
}
.SPASample audio,
.SPASample canvas,
.SPASample progress,
.SPASample video {
  display: inline-block;
  vertical-align: baseline;
}
.SPASample audio:not([controls]) {
  display: none;
  height: 0;
}
.SPASample [hidden],
.SPASample template {
  display: none;
}
.SPASample a {
  background-color: transparent;
}
.SPASample a:active,
.SPASample a:hover {
  outline: 0;
}
.SPASample abbr[title] {
  border-bottom: 1px dotted;
}
.SPASample b,
.SPASample strong {
  font-weight: bold;
}
.SPASample dfn {
  font-style: italic;
}
.SPASample h1 {
  margin: .67em 0;
  font-size: 2em;
}
.SPASample mark {
  color: #000;
  background: #ff0;
}
.SPASample small {
  font-size: 80%;
}
.SPASample sub,
.SPASample sup {
  position: relative;
  font-size: 75%;
  line-height: 0;
  vertical-align: baseline;
}
.SPASample sup {
  top: -0.5em;
}
.SPASample sub {
  bottom: -0.25em;
}
.SPASample img {
  border: 0;
}
.SPASample svg:not(:root) {
  overflow: hidden;
}
.SPASample figure {
  margin: 1em 40px;
}
.SPASample hr {
  height: 0;
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
}
.SPASample pre {
  overflow: auto;
}
.SPASample code,
.SPASample kbd,
.SPASample pre,
.SPASample samp {
  font-family: monospace, monospace;
  font-size: 1em;
}
.SPASample button,
.SPASample input,
.SPASample optgroup,
.SPASample select,
.SPASample textarea {
  margin: 0;
  font: inherit;
  color: inherit;
}
.SPASample button {
  overflow: visible;
}
.SPASample button,
.SPASample select {
  text-transform: none;
}
.SPASample button,
.SPASample html input[type="button"],
.SPASample input[type="reset"],
.SPASample input[type="submit"] {
  -webkit-appearance: button;
  cursor: pointer;
}
.SPASample button[disabled],
.SPASample html input[disabled] {
  cursor: default;
}
.SPASample button::-moz-focus-inner,
.SPASample input::-moz-focus-inner {
  padding: 0;
  border: 0;
}
.SPASample input {
  line-height: normal;
}
.SPASample input[type="checkbox"],
.SPASample input[type="radio"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  padding: 0;
}
.SPASample input[type="number"]::-webkit-inner-spin-button,
.SPASample input[type="number"]::-webkit-outer-spin-button {
  height: auto;
}
.SPASample input[type="search"] {
  -webkit-box-sizing: content-box;
  -moz-box-sizing: content-box;
  box-sizing: content-box;
  -webkit-appearance: textfield;
}
.SPASample input[type="search"]::-webkit-search-cancel-button,
.SPASample input[type="search"]::-webkit-search-decoration {
  -webkit-appearance: none;
}
.SPASample fieldset {
  padding: .35em .625em .75em;
  margin: 0 2px;
  border: 1px solid #c0c0c0;
}
.SPASample legend {
  padding: 0;
  border: 0;
}
.SPASample textarea {
  overflow: auto;
}
.SPASample optgroup {
  font-weight: bold;
}
.SPASample table {
  border-spacing: 0;
  border-collapse: collapse;
}
.SPASample td,
.SPASample th {
  padding: 0;
}
@media print {
  .SPASample *,
  .SPASample *:before,
  .SPASample *:after {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
  }
  .SPASample a,
  .SPASample a:visited {
    text-decoration: underline;
  }
  .SPASample a[href]:after {
    content: " (" attr(href) ")";
  }
  .SPASample abbr[title]:after {
    content: " (" attr(title) ")";
  }
  .SPASample a[href^="#"]:after,
  .SPASample a[href^="javascript:"]:after {
    content: "";
  }
  .SPASample pre,
  .SPASample blockquote {
    border: 1px solid #999;
    page-break-inside: avoid;
  }
  .SPASample thead {
    display: table-header-group;
  }
  .SPASample tr,
  .SPASample img {
    page-break-inside: avoid;
  }
  .SPASample img {
    max-width: 100% !important;
  }
  .SPASample p,
  .SPASample h2,
  .SPASample h3 {
    orphans: 3;
    widows: 3;
  }
  .SPASample h2,
  .SPASample h3 {
    page-break-after: avoid;
  }
  .SPASample select {
    background: #fff !important;
  }
  .SPASample .navbar {
    display: none;
  }
  .SPASample .btn > .caret,
  .SPASample .dropup > .btn > .caret {
    border-top-color: #000 !important;
  }
  .SPASample .label {
    border: 1px solid #000;
  }
  .SPASample .table {
    border-collapse: collapse !important;
  }
  .SPASample .table td,
  .SPASample .table th {
    background-color: #fff !important;
  }
  .SPASample .table-bordered th,
  .SPASample .table-bordered td {
    border: 1px solid #ddd !important;
  }
}
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot');
  src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('../fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('../fonts/glyphicons-halflings-regular.woff') format('woff'), url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
.SPASample .glyphicon {
  position: relative;
  top: 1px;
  display: inline-block;
  font-family: 'Glyphicons Halflings';
  font-style: normal;
  font-weight: normal;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.SPASample .glyphicon-asterisk:before {
  content: "\2a";
}
.SPASample .glyphicon-plus:before {
  content: "\2b";
}
.SPASample .glyphicon-euro:before,
.SPASample .glyphicon-eur:before {
  content: "\20ac";
}
.SPASample .glyphicon-minus:before {
  content: "\2212";
}
.SPASample .glyphicon-cloud:before {
  content: "\2601";
}
.SPASample .glyphicon-envelope:before {
  content: "\2709";
}
.SPASample .glyphicon-pencil:before {
  content: "\270f";
}
.SPASample .glyphicon-glass:before {
  content: "\e001";
}
.SPASample .glyphicon-music:before {
  content: "\e002";
}
.SPASample .glyphicon-search:before {
  content: "\e003";
}
.SPASample .glyphicon-heart:before {
  content: "\e005";
}
.SPASample .glyphicon-star:before {
  content: "\e006";
}
.SPASample .glyphicon-star-empty:before {
  content: "\e007";
}
.SPASample .glyphicon-user:before {
  content: "\e008";
}
.SPASample .glyphicon-film:before {
  content: "\e009";
}
.SPASample .glyphicon-th-large:before {
  content: "\e010";
}
.SPASample .glyphicon-th:before {
  content: "\e011";
}
.SPASample .glyphicon-th-list:before {
  content: "\e012";
}
.SPASample .glyphicon-ok:before {
  content: "\e013";
}
.SPASample .glyphicon-remove:before {
  content: "\e014";
}
.SPASample .glyphicon-zoom-in:before {
  content: "\e015";
}
.SPASample .glyphicon-zoom-out:before {
  content: "\e016";
}
.SPASample .glyphicon-off:before {
  content: "\e017";
}
.SPASample .glyphicon-signal:before {
  content: "\e018";
}
.SPASample .glyphicon-cog:before {
  content: "\e019";
}
.SPASample .glyphicon-trash:before {
  content: "\e020";
}
.SPASample .glyphicon-home:before {
  content: "\e021";
}
.SPASample .glyphicon-file:before {
  content: "\e022";
}
.SPASample .glyphicon-time:before {
  content: "\e023";
}
.SPASample .glyphicon-road:before {
  content: "\e024";
}
.SPASample .glyphicon-download-alt:before {
  content: "\e025";
}
.SPASample .glyphicon-download:before {
  content: "\e026";
}
.SPASample .glyphicon-upload:before {
  content: "\e027";
}
.SPASample .glyphicon-inbox:before {
  content: "\e028";
}
.SPASample .glyphicon-play-circle:before {
  content: "\e029";
}
.SPASample .glyphicon-repeat:before {
  content: "\e030";
}
.SPASample .glyphicon-refresh:before {
  content: "\e031";
}
.SPASample .glyphicon-list-alt:before {
  content: "\e032";
}
.SPASample .glyphicon-lock:before {
  content: "\e033";
}
.SPASample .glyphicon-flag:before {
  content: "\e034";
}
.SPASample .glyphicon-headphones:before {
  content: "\e035";
}
.SPASample .glyphicon-volume-off:before {
  content: "\e036";
}
.SPASample .glyphicon-volume-down:before {
  content: "\e037";
}
.SPASample .glyphicon-volume-up:before {
  content: "\e038";
}
.SPASample .glyphicon-qrcode:before {
  content: "\e039";
}
.SPASample .glyphicon-barcode:before {
  content: "\e040";
}
.SPASample .glyphicon-tag:before {
  content: "\e041";
}
.SPASample .glyphicon-tags:before {
  content: "\e042";
}
.SPASample .glyphicon-book:before {
  content: "\e043";
}
.SPASample .glyphicon-bookmark:before {
  content: "\e044";
}
.SPASample .glyphicon-print:before {
  content: "\e045";
}
.SPASample .glyphicon-camera:before {
  content: "\e046";
}
.SPASample .glyphicon-font:before {
  content: "\e047";
}
.SPASample .glyphicon-bold:before {
  content: "\e048";
}
.SPASample .glyphicon-italic:before {
  content: "\e049";
}
.SPASample .glyphicon-text-height:before {
  content: "\e050";
}
.SPASample .glyphicon-text-width:before {
  content: "\e051";
}
.SPASample .glyphicon-align-left:before {
  content: "\e052";
}
.SPASample .glyphicon-align-center:before {
  content: "\e053";
}
.SPASample .glyphicon-align-right:before {
  content: "\e054";
}
.SPASample .glyphicon-align-justify:before {
  content: "\e055";
}
.SPASample .glyphicon-list:before {
  content: "\e056";
}
.SPASample .glyphicon-indent-left:before {
  content: "\e057";
}
.SPASample .glyphicon-indent-right:before {
  content: "\e058";
}
.SPASample .glyphicon-facetime-video:before {
  content: "\e059";
}
.SPASample .glyphicon-picture:before {
  content: "\e060";
}
.SPASample .glyphicon-map-marker:before {
  content: "\e062";
}
.SPASample .glyphicon-adjust:before {
  content: "\e063";
}
.SPASample .glyphicon-tint:before {
  content: "\e064";
}
.SPASample .glyphicon-edit:before {
  content: "\e065";
}
.SPASample .glyphicon-share:before {
  content: "\e066";
}
.SPASample .glyphicon-check:before {
  content: "\e067";
}
.SPASample .glyphicon-move:before {
  content: "\e068";
}
.SPASample .glyphicon-step-backward:before {
  content: "\e069";
}
.SPASample .glyphicon-fast-backward:before {
  content: "\e070";
}
.SPASample .glyphicon-backward:before {
  content: "\e071";
}
.SPASample .glyphicon-play:before {
  content: "\e072";
}
.SPASample .glyphicon-pause:before {
  content: "\e073";
}
.SPASample .glyphicon-stop:before {
  content: "\e074";
}
.SPASample .glyphicon-forward:before {
  content: "\e075";
}
.SPASample .glyphicon-fast-forward:before {
  content: "\e076";
}
.SPASample .glyphicon-step-forward:before {
  content: "\e077";
}
.SPASample .glyphicon-eject:before {
  content: "\e078";
}
.SPASample .glyphicon-chevron-left:before {
  content: "\e079";
}
.SPASample .glyphicon-chevron-right:before {
  content: "\e080";
}
.SPASample .glyphicon-plus-sign:before {
  content: "\e081";
}
.SPASample .glyphicon-minus-sign:before {
  content: "\e082";
}
.SPASample .glyphicon-remove-sign:before {
  content: "\e083";
}
.SPASample .glyphicon-ok-sign:before {
  content: "\e084";
}
.SPASample .glyphicon-question-sign:before {
  content: "\e085";
}
.SPASample .glyphicon-info-sign:before {
  content: "\e086";
}
.SPASample .glyphicon-screenshot:before {
  content: "\e087";
}
.SPASample .glyphicon-remove-circle:before {
  content: "\e088";
}
.SPASample .glyphicon-ok-circle:before {
  content: "\e089";
}
.SPASample .glyphicon-ban-circle:before {
  content: "\e090";
}
.SPASample .glyphicon-arrow-left:before {
  content: "\e091";
}
.SPASample .glyphicon-arrow-right:before {
  content: "\e092";
}
.SPASample .glyphicon-arrow-up:before {
  content: "\e093";
}
.SPASample .glyphicon-arrow-down:before {
  content: "\e094";
}
.SPASample .glyphicon-share-alt:before {
  content: "\e095";
}
.SPASample .glyphicon-resize-full:before {
  content: "\e096";
}
.SPASample .glyphicon-resize-small:before {
  content: "\e097";
}
.SPASample .glyphicon-exclamation-sign:before {
  content: "\e101";
}
.SPASample .glyphicon-gift:before {
  content: "\e102";
}
.SPASample .glyphicon-leaf:before {
  content: "\e103";
}
.SPASample .glyphicon-fire:before {
  content: "\e104";
}
.SPASample .glyphicon-eye-open:before {
  content: "\e105";
}
.SPASample .glyphicon-eye-close:before {
  content: "\e106";
}
.SPASample .glyphicon-warning-sign:before {
  content: "\e107";
}
.SPASample .glyphicon-plane:before {
  content: "\e108";
}
.SPASample .glyphicon-calendar:before {
  content: "\e109";
}
.SPASample .glyphicon-random:before {
  content: "\e110";
}
.SPASample .glyphicon-comment:before {
  content: "\e111";
}
.SPASample .glyphicon-magnet:before {
  content: "\e112";
}
.SPASample .glyphicon-chevron-up:before {
  content: "\e113";
}
.SPASample .glyphicon-chevron-down:before {
  content: "\e114";
}
.SPASample .glyphicon-retweet:before {
  content: "\e115";
}
.SPASample .glyphicon-shopping-cart:before {
  content: "\e116";
}
.SPASample .glyphicon-folder-close:before {
  content: "\e117";
}
.SPASample .glyphicon-folder-open:before {
  content: "\e118";
}
.SPASample .glyphicon-resize-vertical:before {
  content: "\e119";
}
.SPASample .glyphicon-resize-horizontal:before {
  content: "\e120";
}
.SPASample .glyphicon-hdd:before {
  content: "\e121";
}
.SPASample .glyphicon-bullhorn:before {
  content: "\e122";
}
.SPASample .glyphicon-bell:before {
  content: "\e123";
}
.SPASample .glyphicon-certificate:before {
  content: "\e124";
}
.SPASample .glyphicon-thumbs-up:before {
  content: "\e125";
}
.SPASample .glyphicon-thumbs-down:before {
  content: "\e126";
}
.SPASample .glyphicon-hand-right:before {
  content: "\e127";
}
.SPASample .glyphicon-hand-left:before {
  content: "\e128";
}
.SPASample .glyphicon-hand-up:before {
  content: "\e129";
}
.SPASample .glyphicon-hand-down:before {
  content: "\e130";
}
.SPASample .glyphicon-circle-arrow-right:before {
  content: "\e131";
}
.SPASample .glyphicon-circle-arrow-left:before {
  content: "\e132";
}
.SPASample .glyphicon-circle-arrow-up:before {
  content: "\e133";
}
.SPASample .glyphicon-circle-arrow-down:before {
  content: "\e134";
}
.SPASample .glyphicon-globe:before {
  content: "\e135";
}
.SPASample .glyphicon-wrench:before {
  content: "\e136";
}
.SPASample .glyphicon-tasks:before {
  content: "\e137";
}
.SPASample .glyphicon-filter:before {
  content: "\e138";
}
.SPASample .glyphicon-briefcase:before {
  content: "\e139";
}
.SPASample .glyphicon-fullscreen:before {
  content: "\e140";
}
.SPASample .glyphicon-dashboard:before {
  content: "\e141";
}
.SPASample .glyphicon-paperclip:before {
  content: "\e142";
}
.SPASample .glyphicon-heart-empty:before {
  content: "\e143";
}
.SPASample .glyphicon-link:before {
  content: "\e144";
}
.SPASample .glyphicon-phone:before {
  content: "\e145";
}
.SPASample .glyphicon-pushpin:before {
  content: "\e146";
}
.SPASample .glyphicon-usd:before {
  content: "\e148";
}
.SPASample .glyphicon-gbp:before {
  content: "\e149";
}
.SPASample .glyphicon-sort:before {
  content: "\e150";
}
.SPASample .glyphicon-sort-by-alphabet:before {
  content: "\e151";
}
.SPASample .glyphicon-sort-by-alphabet-alt:before {
  content: "\e152";
}
.SPASample .glyphicon-sort-by-order:before {
  content: "\e153";
}
.SPASample .glyphicon-sort-by-order-alt:before {
  content: "\e154";
}
.SPASample .glyphicon-sort-by-attributes:before {
  content: "\e155";
}
.SPASample .glyphicon-sort-by-attributes-alt:before {
  content: "\e156";
}
.SPASample .glyphicon-unchecked:before {
  content: "\e157";
}
.SPASample .glyphicon-expand:before {
  content: "\e158";
}
.SPASample .glyphicon-collapse-down:before {
  content: "\e159";
}
.SPASample .glyphicon-collapse-up:before {
  content: "\e160";
}
.SPASample .glyphicon-log-in:before {
  content: "\e161";
}
.SPASample .glyphicon-flash:before {
  content: "\e162";
}
.SPASample .glyphicon-log-out:before {
  content: "\e163";
}
.SPASample .glyphicon-new-window:before {
  content: "\e164";
}
.SPASample .glyphicon-record:before {
  content: "\e165";
}
.SPASample .glyphicon-save:before {
  content: "\e166";
}
.SPASample .glyphicon-open:before {
  content: "\e167";
}
.SPASample .glyphicon-saved:before {
  content: "\e168";
}
.SPASample .glyphicon-import:before {
  content: "\e169";
}
.SPASample .glyphicon-export:before {
  content: "\e170";
}
.SPASample .glyphicon-send:before {
  content: "\e171";
}
.SPASample .glyphicon-floppy-disk:before {
  content: "\e172";
}
.SPASample .glyphicon-floppy-saved:before {
  content: "\e173";
}
.SPASample .glyphicon-floppy-remove:before {
  content: "\e174";
}
.SPASample .glyphicon-floppy-save:before {
  content: "\e175";
}
.SPASample .glyphicon-floppy-open:before {
  content: "\e176";
}
.SPASample .glyphicon-credit-card:before {
  content: "\e177";
}
.SPASample .glyphicon-transfer:before {
  content: "\e178";
}
.SPASample .glyphicon-cutlery:before {
  content: "\e179";
}
.SPASample .glyphicon-header:before {
  content: "\e180";
}
.SPASample .glyphicon-compressed:before {
  content: "\e181";
}
.SPASample .glyphicon-earphone:before {
  content: "\e182";
}
.SPASample .glyphicon-phone-alt:before {
  content: "\e183";
}
.SPASample .glyphicon-tower:before {
  content: "\e184";
}
.SPASample .glyphicon-stats:before {
  content: "\e185";
}
.SPASample .glyphicon-sd-video:before {
  content: "\e186";
}
.SPASample .glyphicon-hd-video:before {
  content: "\e187";
}
.SPASample .glyphicon-subtitles:before {
  content: "\e188";
}
.SPASample .glyphicon-sound-stereo:before {
  content: "\e189";
}
.SPASample .glyphicon-sound-dolby:before {
  content: "\e190";
}
.SPASample .glyphicon-sound-5-1:before {
  content: "\e191";
}
.SPASample .glyphicon-sound-6-1:before {
  content: "\e192";
}
.SPASample .glyphicon-sound-7-1:before {
  content: "\e193";
}
.SPASample .glyphicon-copyright-mark:before {
  content: "\e194";
}
.SPASample .glyphicon-registration-mark:before {
  content: "\e195";
}
.SPASample .glyphicon-cloud-download:before {
  content: "\e197";
}
.SPASample .glyphicon-cloud-upload:before {
  content: "\e198";
}
.SPASample .glyphicon-tree-conifer:before {
  content: "\e199";
}
.SPASample .glyphicon-tree-deciduous:before {
  content: "\e200";
}
.SPASample .glyphicon-cd:before {
  content: "\e201";
}
.SPASample .glyphicon-save-file:before {
  content: "\e202";
}
.SPASample .glyphicon-open-file:before {
  content: "\e203";
}
.SPASample .glyphicon-level-up:before {
  content: "\e204";
}
.SPASample .glyphicon-copy:before {
  content: "\e205";
}
.SPASample .glyphicon-paste:before {
  content: "\e206";
}
.SPASample .glyphicon-alert:before {
  content: "\e209";
}
.SPASample .glyphicon-equalizer:before {
  content: "\e210";
}
.SPASample .glyphicon-king:before {
  content: "\e211";
}
.SPASample .glyphicon-queen:before {
  content: "\e212";
}
.SPASample .glyphicon-pawn:before {
  content: "\e213";
}
.SPASample .glyphicon-bishop:before {
  content: "\e214";
}
.SPASample .glyphicon-knight:before {
  content: "\e215";
}
.SPASample .glyphicon-baby-formula:before {
  content: "\e216";
}
.SPASample .glyphicon-tent:before {
  content: "\26fa";
}
.SPASample .glyphicon-blackboard:before {
  content: "\e218";
}
.SPASample .glyphicon-bed:before {
  content: "\e219";
}
.SPASample .glyphicon-apple:before {
  content: "\f8ff";
}
.SPASample .glyphicon-erase:before {
  content: "\e221";
}
.SPASample .glyphicon-hourglass:before {
  content: "\231b";
}
.SPASample .glyphicon-lamp:before {
  content: "\e223";
}
.SPASample .glyphicon-duplicate:before {
  content: "\e224";
}
.SPASample .glyphicon-piggy-bank:before {
  content: "\e225";
}
.SPASample .glyphicon-scissors:before {
  content: "\e226";
}
.SPASample .glyphicon-bitcoin:before {
  content: "\e227";
}
.SPASample .glyphicon-btc:before {
  content: "\e227";
}
.SPASample .glyphicon-xbt:before {
  content: "\e227";
}
.SPASample .glyphicon-yen:before {
  content: "\00a5";
}
.SPASample .glyphicon-jpy:before {
  content: "\00a5";
}
.SPASample .glyphicon-ruble:before {
  content: "\20bd";
}
.SPASample .glyphicon-rub:before {
  content: "\20bd";
}
.SPASample .glyphicon-scale:before {
  content: "\e230";
}
.SPASample .glyphicon-ice-lolly:before {
  content: "\e231";
}
.SPASample .glyphicon-ice-lolly-tasted:before {
  content: "\e232";
}
.SPASample .glyphicon-education:before {
  content: "\e233";
}
.SPASample .glyphicon-option-horizontal:before {
  content: "\e234";
}
.SPASample .glyphicon-option-vertical:before {
  content: "\e235";
}
.SPASample .glyphicon-menu-hamburger:before {
  content: "\e236";
}
.SPASample .glyphicon-modal-window:before {
  content: "\e237";
}
.SPASample .glyphicon-oil:before {
  content: "\e238";
}
.SPASample .glyphicon-grain:before {
  content: "\e239";
}
.SPASample .glyphicon-sunglasses:before {
  content: "\e240";
}
.SPASample .glyphicon-text-size:before {
  content: "\e241";
}
.SPASample .glyphicon-text-color:before {
  content: "\e242";
}
.SPASample .glyphicon-text-background:before {
  content: "\e243";
}
.SPASample .glyphicon-object-align-top:before {
  content: "\e244";
}
.SPASample .glyphicon-object-align-bottom:before {
  content: "\e245";
}
.SPASample .glyphicon-object-align-horizontal:before {
  content: "\e246";
}
.SPASample .glyphicon-object-align-left:before {
  content: "\e247";
}
.SPASample .glyphicon-object-align-vertical:before {
  content: "\e248";
}
.SPASample .glyphicon-object-align-right:before {
  content: "\e249";
}
.SPASample .glyphicon-triangle-right:before {
  content: "\e250";
}
.SPASample .glyphicon-triangle-left:before {
  content: "\e251";
}
.SPASample .glyphicon-triangle-bottom:before {
  content: "\e252";
}
.SPASample .glyphicon-triangle-top:before {
  content: "\e253";
}
.SPASample .glyphicon-console:before {
  content: "\e254";
}
.SPASample .glyphicon-superscript:before {
  content: "\e255";
}
.SPASample .glyphicon-subscript:before {
  content: "\e256";
}
.SPASample .glyphicon-menu-left:before {
  content: "\e257";
}
.SPASample .glyphicon-menu-right:before {
  content: "\e258";
}
.SPASample .glyphicon-menu-down:before {
  content: "\e259";
}
.SPASample .glyphicon-menu-up:before {
  content: "\e260";
}
.SPASample * {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
.SPASample *:before,
.SPASample *:after {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
.SPASample html {
  font-size: 10px;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
.SPASample body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}
.SPASample input,
.SPASample button,
.SPASample select,
.SPASample textarea {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}
.SPASample a {
  color: #337ab7;
  text-decoration: none;
}
.SPASample a:hover,
.SPASample a:focus {
  color: #23527c;
  text-decoration: underline;
}
.SPASample a:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
.SPASample figure {
  margin: 0;
}
.SPASample img {
  vertical-align: middle;
}
.SPASample .img-responsive,
.SPASample .thumbnail > img,
.SPASample .thumbnail a > img,
.SPASample .carousel-inner > .item > img,
.SPASample .carousel-inner > .item > a > img {
  display: block;
  max-width: 100%;
  height: auto;
}
.SPASample .img-rounded {
  border-radius: 6px;
}
.SPASample .img-thumbnail {
  display: inline-block;
  max-width: 100%;
  height: auto;
  padding: 4px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: all 0.2s ease-in-out;
  -o-transition: all 0.2s ease-in-out;
  transition: all 0.2s ease-in-out;
}
.SPASample .img-circle {
  border-radius: 50%;
}
.SPASample hr {
  margin-top: 20px;
  margin-bottom: 20px;
  border: 0;
  border-top: 1px solid #eee;
}
.SPASample .sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  border: 0;
}
.SPASample .sr-only-focusable:active,
.SPASample .sr-only-focusable:focus {
  position: static;
  width: auto;
  height: auto;
  margin: 0;
  overflow: visible;
  clip: auto;
}
.SPASample [role="button"] {
  cursor: pointer;
}
.SPASample h1,
.SPASample h2,
.SPASample h3,
.SPASample h4,
.SPASample h5,
.SPASample h6,
.SPASample .h1,
.SPASample .h2,
.SPASample .h3,
.SPASample .h4,
.SPASample .h5,
.SPASample .h6 {
  font-family: inherit;
  font-weight: 500;
  line-height: 1.1;
  color: inherit;
}
.SPASample h1 small,
.SPASample h2 small,
.SPASample h3 small,
.SPASample h4 small,
.SPASample h5 small,
.SPASample h6 small,
.SPASample .h1 small,
.SPASample .h2 small,
.SPASample .h3 small,
.SPASample .h4 small,
.SPASample .h5 small,
.SPASample .h6 small,
.SPASample h1 .small,
.SPASample h2 .small,
.SPASample h3 .small,
.SPASample h4 .small,
.SPASample h5 .small,
.SPASample h6 .small,
.SPASample .h1 .small,
.SPASample .h2 .small,
.SPASample .h3 .small,
.SPASample .h4 .small,
.SPASample .h5 .small,
.SPASample .h6 .small {
  font-weight: normal;
  line-height: 1;
  color: #777;
}
.SPASample h1,
.SPASample .h1,
.SPASample h2,
.SPASample .h2,
.SPASample h3,
.SPASample .h3 {
  margin-top: 20px;
  margin-bottom: 10px;
}
.SPASample h1 small,
.SPASample .h1 small,
.SPASample h2 small,
.SPASample .h2 small,
.SPASample h3 small,
.SPASample .h3 small,
.SPASample h1 .small,
.SPASample .h1 .small,
.SPASample h2 .small,
.SPASample .h2 .small,
.SPASample h3 .small,
.SPASample .h3 .small {
  font-size: 65%;
}
.SPASample h4,
.SPASample .h4,
.SPASample h5,
.SPASample .h5,
.SPASample h6,
.SPASample .h6 {
  margin-top: 10px;
  margin-bottom: 10px;
}
.SPASample h4 small,
.SPASample .h4 small,
.SPASample h5 small,
.SPASample .h5 small,
.SPASample h6 small,
.SPASample .h6 small,
.SPASample h4 .small,
.SPASample .h4 .small,
.SPASample h5 .small,
.SPASample .h5 .small,
.SPASample h6 .small,
.SPASample .h6 .small {
  font-size: 75%;
}
.SPASample h1,
.SPASample .h1 {
  font-size: 36px;
}
.SPASample h2,
.SPASample .h2 {
  font-size: 30px;
}
.SPASample h3,
.SPASample .h3 {
  font-size: 24px;
}
.SPASample h4,
.SPASample .h4 {
  font-size: 18px;
}
.SPASample h5,
.SPASample .h5 {
  font-size: 14px;
}
.SPASample h6,
.SPASample .h6 {
  font-size: 12px;
}
.SPASample p {
  margin: 0 0 10px;
}
.SPASample .lead {
  margin-bottom: 20px;
  font-size: 16px;
  font-weight: 300;
  line-height: 1.4;
}
@media (min-width: 768px) {
  .SPASample .lead {
    font-size: 21px;
  }
}
.SPASample small,
.SPASample .small {
  font-size: 85%;
}
.SPASample mark,
.SPASample .mark {
  padding: .2em;
  background-color: #fcf8e3;
}
.SPASample .text-left {
  text-align: left;
}
.SPASample .text-right {
  text-align: right;
}
.SPASample .text-center {
  text-align: center;
}
.SPASample .text-justify {
  text-align: justify;
}
.SPASample .text-nowrap {
  white-space: nowrap;
}
.SPASample .text-lowercase {
  text-transform: lowercase;
}
.SPASample .text-uppercase {
  text-transform: uppercase;
}
.SPASample .text-capitalize {
  text-transform: capitalize;
}
.SPASample .text-muted {
  color: #777;
}
.SPASample .text-primary {
  color: #337ab7;
}
.SPASample a.text-primary:hover {
  color: #286090;
}
.SPASample .text-success {
  color: #3c763d;
}
.SPASample a.text-success:hover {
  color: #2b542c;
}
.SPASample .text-info {
  color: #31708f;
}
.SPASample a.text-info:hover {
  color: #245269;
}
.SPASample .text-warning {
  color: #8a6d3b;
}
.SPASample a.text-warning:hover {
  color: #66512c;
}
.SPASample .text-danger {
  color: #a94442;
}
.SPASample a.text-danger:hover {
  color: #843534;
}
.SPASample .bg-primary {
  color: #fff;
  background-color: #337ab7;
}
.SPASample a.bg-primary:hover {
  background-color: #286090;
}
.SPASample .bg-success {
  background-color: #dff0d8;
}
.SPASample a.bg-success:hover {
  background-color: #c1e2b3;
}
.SPASample .bg-info {
  background-color: #d9edf7;
}
.SPASample a.bg-info:hover {
  background-color: #afd9ee;
}
.SPASample .bg-warning {
  background-color: #fcf8e3;
}
.SPASample a.bg-warning:hover {
  background-color: #f7ecb5;
}
.SPASample .bg-danger {
  background-color: #f2dede;
}
.SPASample a.bg-danger:hover {
  background-color: #e4b9b9;
}
.SPASample .page-header {
  padding-bottom: 9px;
  margin: 40px 0 20px;
  border-bottom: 1px solid #eee;
}
.SPASample ul,
.SPASample ol {
  margin-top: 0;
  margin-bottom: 10px;
}
.SPASample ul ul,
.SPASample ol ul,
.SPASample ul ol,
.SPASample ol ol {
  margin-bottom: 0;
}
.SPASample .list-unstyled {
  padding-left: 0;
  list-style: none;
}
.SPASample .list-inline {
  padding-left: 0;
  margin-left: -5px;
  list-style: none;
}
.SPASample .list-inline > li {
  display: inline-block;
  padding-right: 5px;
  padding-left: 5px;
}
.SPASample dl {
  margin-top: 0;
  margin-bottom: 20px;
}
.SPASample dt,
.SPASample dd {
  line-height: 1.42857143;
}
.SPASample dt {
  font-weight: bold;
}
.SPASample dd {
  margin-left: 0;
}
@media (min-width: 768px) {
  .SPASample .dl-horizontal dt {
    float: left;
    width: 160px;
    overflow: hidden;
    clear: left;
    text-align: right;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .SPASample .dl-horizontal dd {
    margin-left: 180px;
  }
}
.SPASample abbr[title],
.SPASample abbr[data-original-title] {
  cursor: help;
  border-bottom: 1px dotted #777;
}
.SPASample .initialism {
  font-size: 90%;
  text-transform: uppercase;
}
.SPASample blockquote {
  padding: 10px 20px;
  margin: 0 0 20px;
  font-size: 17.5px;
  border-left: 5px solid #eee;
}
.SPASample blockquote p:last-child,
.SPASample blockquote ul:last-child,
.SPASample blockquote ol:last-child {
  margin-bottom: 0;
}
.SPASample blockquote footer,
.SPASample blockquote small,
.SPASample blockquote .small {
  display: block;
  font-size: 80%;
  line-height: 1.42857143;
  color: #777;
}
.SPASample blockquote footer:before,
.SPASample blockquote small:before,
.SPASample blockquote .small:before {
  content: '\2014 \00A0';
}
.SPASample .blockquote-reverse,
.SPASample blockquote.pull-right {
  padding-right: 15px;
  padding-left: 0;
  text-align: right;
  border-right: 5px solid #eee;
  border-left: 0;
}
.SPASample .blockquote-reverse footer:before,
.SPASample blockquote.pull-right footer:before,
.SPASample .blockquote-reverse small:before,
.SPASample blockquote.pull-right small:before,
.SPASample .blockquote-reverse .small:before,
.SPASample blockquote.pull-right .small:before {
  content: '';
}
.SPASample .blockquote-reverse footer:after,
.SPASample blockquote.pull-right footer:after,
.SPASample .blockquote-reverse small:after,
.SPASample blockquote.pull-right small:after,
.SPASample .blockquote-reverse .small:after,
.SPASample blockquote.pull-right .small:after {
  content: '\00A0 \2014';
}
.SPASample address {
  margin-bottom: 20px;
  font-style: normal;
  line-height: 1.42857143;
}
.SPASample code,
.SPASample kbd,
.SPASample pre,
.SPASample samp {
  font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
}
.SPASample code {
  padding: 2px 4px;
  font-size: 90%;
  color: #c7254e;
  background-color: #f9f2f4;
  border-radius: 4px;
}
.SPASample kbd {
  padding: 2px 4px;
  font-size: 90%;
  color: #fff;
  background-color: #333;
  border-radius: 3px;
  -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.25);
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.25);
}
.SPASample kbd kbd {
  padding: 0;
  font-size: 100%;
  font-weight: bold;
  -webkit-box-shadow: none;
  box-shadow: none;
}
.SPASample pre {
  display: block;
  padding: 9.5px;
  margin: 0 0 10px;
  font-size: 13px;
  line-height: 1.42857143;
  color: #333;
  word-break: break-all;
  word-wrap: break-word;
  background-color: #f5f5f5;
  border: 1px solid #ccc;
  border-radius: 4px;
}
.SPASample pre code {
  padding: 0;
  font-size: inherit;
  color: inherit;
  white-space: pre-wrap;
  background-color: transparent;
  border-radius: 0;
}
.SPASample .pre-scrollable {
  max-height: 340px;
  overflow-y: scroll;
}
.SPASample .container {
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
@media (min-width: 768px) {
  .SPASample .container {
    width: 750px;
  }
}
@media (min-width: 992px) {
  .SPASample .container {
    width: 970px;
  }
}
@media (min-width: 1200px) {
  .SPASample .container {
    width: 1170px;
  }
}
.SPASample .container-fluid {
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
.SPASample .row {
  margin-right: -15px;
  margin-left: -15px;
}
.SPASample .col-xs-1,
.SPASample .col-sm-1,
.SPASample .col-md-1,
.SPASample .col-lg-1,
.SPASample .col-xs-2,
.SPASample .col-sm-2,
.SPASample .col-md-2,
.SPASample .col-lg-2,
.SPASample .col-xs-3,
.SPASample .col-sm-3,
.SPASample .col-md-3,
.SPASample .col-lg-3,
.SPASample .col-xs-4,
.SPASample .col-sm-4,
.SPASample .col-md-4,
.SPASample .col-lg-4,
.SPASample .col-xs-5,
.SPASample .col-sm-5,
.SPASample .col-md-5,
.SPASample .col-lg-5,
.SPASample .col-xs-6,
.SPASample .col-sm-6,
.SPASample .col-md-6,
.SPASample .col-lg-6,
.SPASample .col-xs-7,
.SPASample .col-sm-7,
.SPASample .col-md-7,
.SPASample .col-lg-7,
.SPASample .col-xs-8,
.SPASample .col-sm-8,
.SPASample .col-md-8,
.SPASample .col-lg-8,
.SPASample .col-xs-9,
.SPASample .col-sm-9,
.SPASample .col-md-9,
.SPASample .col-lg-9,
.SPASample .col-xs-10,
.SPASample .col-sm-10,
.SPASample .col-md-10,
.SPASample .col-lg-10,
.SPASample .col-xs-11,
.SPASample .col-sm-11,
.SPASample .col-md-11,
.SPASample .col-lg-11,
.SPASample .col-xs-12,
.SPASample .col-sm-12,
.SPASample .col-md-12,
.SPASample .col-lg-12 {
  position: relative;
  min-height: 1px;
  padding-right: 15px;
  padding-left: 15px;
}
.SPASample .col-xs-1,
.SPASample .col-xs-2,
.SPASample .col-xs-3,
.SPASample .col-xs-4,
.SPASample .col-xs-5,
.SPASample .col-xs-6,
.SPASample .col-xs-7,
.SPASample .col-xs-8,
.SPASample .col-xs-9,
.SPASample .col-xs-10,
.SPASample .col-xs-11,
.SPASample .col-xs-12 {
  float: left;
}
.SPASample .col-xs-12 {
  width: 100%;
}
.SPASample .col-xs-11 {
  width: 91.66666667%;
}
.SPASample .col-xs-10 {
  width: 83.33333333%;
}
.SPASample .col-xs-9 {
  width: 75%;
}
.SPASample .col-xs-8 {
  width: 66.66666667%;
}
.SPASample .col-xs-7 {
  width: 58.33333333%;
}
.SPASample .col-xs-6 {
  width: 50%;
}
.SPASample .col-xs-5 {
  width: 41.66666667%;
}
.SPASample .col-xs-4 {
  width: 33.33333333%;
}
.SPASample .col-xs-3 {
  width: 25%;
}
.SPASample .col-xs-2 {
  width: 16.66666667%;
}
.SPASample .col-xs-1 {
  width: 8.33333333%;
}
.SPASample .col-xs-pull-12 {
  right: 100%;
}
.SPASample .col-xs-pull-11 {
  right: 91.66666667%;
}
.SPASample .col-xs-pull-10 {
  right: 83.33333333%;
}
.SPASample .col-xs-pull-9 {
  right: 75%;
}
.SPASample .col-xs-pull-8 {
  right: 66.66666667%;
}
.SPASample .col-xs-pull-7 {
  right: 58.33333333%;
}
.SPASample .col-xs-pull-6 {
  right: 50%;
}
.SPASample .col-xs-pull-5 {
  right: 41.66666667%;
}
.SPASample .col-xs-pull-4 {
  right: 33.33333333%;
}
.SPASample .col-xs-pull-3 {
  right: 25%;
}
.SPASample .col-xs-pull-2 {
  right: 16.66666667%;
}
.SPASample .col-xs-pull-1 {
  right: 8.33333333%;
}
.SPASample .col-xs-pull-0 {
  right: auto;
}
.SPASample .col-xs-push-12 {
  left: 100%;
}
.SPASample .col-xs-push-11 {
  left: 91.66666667%;
}
.SPASample .col-xs-push-10 {
  left: 83.33333333%;
}
.SPASample .col-xs-push-9 {
  left: 75%;
}
.SPASample .col-xs-push-8 {
  left: 66.66666667%;
}
.SPASample .col-xs-push-7 {
  left: 58.33333333%;
}
.SPASample .col-xs-push-6 {
  left: 50%;
}
.SPASample .col-xs-push-5 {
  left: 41.66666667%;
}
.SPASample .col-xs-push-4 {
  left: 33.33333333%;
}
.SPASample .col-xs-push-3 {
  left: 25%;
}
.SPASample .col-xs-push-2 {
  left: 16.66666667%;
}
.SPASample .col-xs-push-1 {
  left: 8.33333333%;
}
.SPASample .col-xs-push-0 {
  left: auto;
}
.SPASample .col-xs-offset-12 {
  margin-left: 100%;
}
.SPASample .col-xs-offset-11 {
  margin-left: 91.66666667%;
}
.SPASample .col-xs-offset-10 {
  margin-left: 83.33333333%;
}
.SPASample .col-xs-offset-9 {
  margin-left: 75%;
}
.SPASample .col-xs-offset-8 {
  margin-left: 66.66666667%;
}
.SPASample .col-xs-offset-7 {
  margin-left: 58.33333333%;
}
.SPASample .col-xs-offset-6 {
  margin-left: 50%;
}
.SPASample .col-xs-offset-5 {
  margin-left: 41.66666667%;
}
.SPASample .col-xs-offset-4 {
  margin-left: 33.33333333%;
}
.SPASample .col-xs-offset-3 {
  margin-left: 25%;
}
.SPASample .col-xs-offset-2 {
  margin-left: 16.66666667%;
}
.SPASample .col-xs-offset-1 {
  margin-left: 8.33333333%;
}
.SPASample .col-xs-offset-0 {
  margin-left: 0;
}
@media (min-width: 768px) {
  .SPASample .col-sm-1,
  .SPASample .col-sm-2,
  .SPASample .col-sm-3,
  .SPASample .col-sm-4,
  .SPASample .col-sm-5,
  .SPASample .col-sm-6,
  .SPASample .col-sm-7,
  .SPASample .col-sm-8,
  .SPASample .col-sm-9,
  .SPASample .col-sm-10,
  .SPASample .col-sm-11,
  .SPASample .col-sm-12 {
    float: left;
  }
  .SPASample .col-sm-12 {
    width: 100%;
  }
  .SPASample .col-sm-11 {
    width: 91.66666667%;
  }
  .SPASample .col-sm-10 {
    width: 83.33333333%;
  }
  .SPASample .col-sm-9 {
    width: 75%;
  }
  .SPASample .col-sm-8 {
    width: 66.66666667%;
  }
  .SPASample .col-sm-7 {
    width: 58.33333333%;
  }
  .SPASample .col-sm-6 {
    width: 50%;
  }
  .SPASample .col-sm-5 {
    width: 41.66666667%;
  }
  .SPASample .col-sm-4 {
    width: 33.33333333%;
  }
  .SPASample .col-sm-3 {
    width: 25%;
  }
  .SPASample .col-sm-2 {
    width: 16.66666667%;
  }
  .SPASample .col-sm-1 {
    width: 8.33333333%;
  }
  .SPASample .col-sm-pull-12 {
    right: 100%;
  }
  .SPASample .col-sm-pull-11 {
    right: 91.66666667%;
  }
  .SPASample .col-sm-pull-10 {
    right: 83.33333333%;
  }
  .SPASample .col-sm-pull-9 {
    right: 75%;
  }
  .SPASample .col-sm-pull-8 {
    right: 66.66666667%;
  }
  .SPASample .col-sm-pull-7 {
    right: 58.33333333%;
  }
  .SPASample .col-sm-pull-6 {
    right: 50%;
  }
  .SPASample .col-sm-pull-5 {
    right: 41.66666667%;
  }
  .SPASample .col-sm-pull-4 {
    right: 33.33333333%;
  }
  .SPASample .col-sm-pull-3 {
    right: 25%;
  }
  .SPASample .col-sm-pull-2 {
    right: 16.66666667%;
  }
  .SPASample .col-sm-pull-1 {
    right: 8.33333333%;
  }
  .SPASample .col-sm-pull-0 {
    right: auto;
  }
  .SPASample .col-sm-push-12 {
    left: 100%;
  }
  .SPASample .col-sm-push-11 {
    left: 91.66666667%;
  }
  .SPASample .col-sm-push-10 {
    left: 83.33333333%;
  }
  .SPASample .col-sm-push-9 {
    left: 75%;
  }
  .SPASample .col-sm-push-8 {
    left: 66.66666667%;
  }
  .SPASample .col-sm-push-7 {
    left: 58.33333333%;
  }
  .SPASample .col-sm-push-6 {
    left: 50%;
  }
  .SPASample .col-sm-push-5 {
    left: 41.66666667%;
  }
  .SPASample .col-sm-push-4 {
    left: 33.33333333%;
  }
  .SPASample .col-sm-push-3 {
    left: 25%;
  }
  .SPASample .col-sm-push-2 {
    left: 16.66666667%;
  }
  .SPASample .col-sm-push-1 {
    left: 8.33333333%;
  }
  .SPASample .col-sm-push-0 {
    left: auto;
  }
  .SPASample .col-sm-offset-12 {
    margin-left: 100%;
  }
  .SPASample .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .SPASample .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .SPASample .col-sm-offset-9 {
    margin-left: 75%;
  }
  .SPASample .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .SPASample .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .SPASample .col-sm-offset-6 {
    margin-left: 50%;
  }
  .SPASample .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .SPASample .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .SPASample .col-sm-offset-3 {
    margin-left: 25%;
  }
  .SPASample .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .SPASample .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .SPASample .col-sm-offset-0 {
    margin-left: 0;
  }
}
@media (min-width: 992px) {
  .SPASample .col-md-1,
  .SPASample .col-md-2,
  .SPASample .col-md-3,
  .SPASample .col-md-4,
  .SPASample .col-md-5,
  .SPASample .col-md-6,
  .SPASample .col-md-7,
  .SPASample .col-md-8,
  .SPASample .col-md-9,
  .SPASample .col-md-10,
  .SPASample .col-md-11,
  .SPASample .col-md-12 {
    float: left;
  }
  .SPASample .col-md-12 {
    width: 100%;
  }
  .SPASample .col-md-11 {
    width: 91.66666667%;
  }
  .SPASample .col-md-10 {
    width: 83.33333333%;
  }
  .SPASample .col-md-9 {
    width: 75%;
  }
  .SPASample .col-md-8 {
    width: 66.66666667%;
  }
  .SPASample .col-md-7 {
    width: 58.33333333%;
  }
  .SPASample .col-md-6 {
    width: 50%;
  }
  .SPASample .col-md-5 {
    width: 41.66666667%;
  }
  .SPASample .col-md-4 {
    width: 33.33333333%;
  }
  .SPASample .col-md-3 {
    width: 25%;
  }
  .SPASample .col-md-2 {
    width: 16.66666667%;
  }
  .SPASample .col-md-1 {
    width: 8.33333333%;
  }
  .SPASample .col-md-pull-12 {
    right: 100%;
  }
  .SPASample .col-md-pull-11 {
    right: 91.66666667%;
  }
  .SPASample .col-md-pull-10 {
    right: 83.33333333%;
  }
  .SPASample .col-md-pull-9 {
    right: 75%;
  }
  .SPASample .col-md-pull-8 {
    right: 66.66666667%;
  }
  .SPASample .col-md-pull-7 {
    right: 58.33333333%;
  }
  .SPASample .col-md-pull-6 {
    right: 50%;
  }
  .SPASample .col-md-pull-5 {
    right: 41.66666667%;
  }
  .SPASample .col-md-pull-4 {
    right: 33.33333333%;
  }
  .SPASample .col-md-pull-3 {
    right: 25%;
  }
  .SPASample .col-md-pull-2 {
    right: 16.66666667%;
  }
  .SPASample .col-md-pull-1 {
    right: 8.33333333%;
  }
  .SPASample .col-md-pull-0 {
    right: auto;
  }
  .SPASample .col-md-push-12 {
    left: 100%;
  }
  .SPASample .col-md-push-11 {
    left: 91.66666667%;
  }
  .SPASample .col-md-push-10 {
    left: 83.33333333%;
  }
  .SPASample .col-md-push-9 {
    left: 75%;
  }
  .SPASample .col-md-push-8 {
    left: 66.66666667%;
  }
  .SPASample .col-md-push-7 {
    left: 58.33333333%;
  }
  .SPASample .col-md-push-6 {
    left: 50%;
  }
  .SPASample .col-md-push-5 {
    left: 41.66666667%;
  }
  .SPASample .col-md-push-4 {
    left: 33.33333333%;
  }
  .SPASample .col-md-push-3 {
    left: 25%;
  }
  .SPASample .col-md-push-2 {
    left: 16.66666667%;
  }
  .SPASample .col-md-push-1 {
    left: 8.33333333%;
  }
  .SPASample .col-md-push-0 {
    left: auto;
  }
  .SPASample .col-md-offset-12 {
    margin-left: 100%;
  }
  .SPASample .col-md-offset-11 {
    margin-left: 91.66666667%;
  }
  .SPASample .col-md-offset-10 {
    margin-left: 83.33333333%;
  }
  .SPASample .col-md-offset-9 {
    margin-left: 75%;
  }
  .SPASample .col-md-offset-8 {
    margin-left: 66.66666667%;
  }
  .SPASample .col-md-offset-7 {
    margin-left: 58.33333333%;
  }
  .SPASample .col-md-offset-6 {
    margin-left: 50%;
  }
  .SPASample .col-md-offset-5 {
    margin-left: 41.66666667%;
  }
  .SPASample .col-md-offset-4 {
    margin-left: 33.33333333%;
  }
  .SPASample .col-md-offset-3 {
    margin-left: 25%;
  }
  .SPASample .col-md-offset-2 {
    margin-left: 16.66666667%;
  }
  .SPASample .col-md-offset-1 {
    margin-left: 8.33333333%;
  }
  .SPASample .col-md-offset-0 {
    margin-left: 0;
  }
}
@media (min-width: 1200px) {
  .SPASample .col-lg-1,
  .SPASample .col-lg-2,
  .SPASample .col-lg-3,
  .SPASample .col-lg-4,
  .SPASample .col-lg-5,
  .SPASample .col-lg-6,
  .SPASample .col-lg-7,
  .SPASample .col-lg-8,
  .SPASample .col-lg-9,
  .SPASample .col-lg-10,
  .SPASample .col-lg-11,
  .SPASample .col-lg-12 {
    float: left;
  }
  .SPASample .col-lg-12 {
    width: 100%;
  }
  .SPASample .col-lg-11 {
    width: 91.66666667%;
  }
  .SPASample .col-lg-10 {
    width: 83.33333333%;
  }
  .SPASample .col-lg-9 {
    width: 75%;
  }
  .SPASample .col-lg-8 {
    width: 66.66666667%;
  }
  .SPASample .col-lg-7 {
    width: 58.33333333%;
  }
  .SPASample .col-lg-6 {
    width: 50%;
  }
  .SPASample .col-lg-5 {
    width: 41.66666667%;
  }
  .SPASample .col-lg-4 {
    width: 33.33333333%;
  }
  .SPASample .col-lg-3 {
    width: 25%;
  }
  .SPASample .col-lg-2 {
    width: 16.66666667%;
  }
  .SPASample .col-lg-1 {
    width: 8.33333333%;
  }
  .SPASample .col-lg-pull-12 {
    right: 100%;
  }
  .SPASample .col-lg-pull-11 {
    right: 91.66666667%;
  }
  .SPASample .col-lg-pull-10 {
    right: 83.33333333%;
  }
  .SPASample .col-lg-pull-9 {
    right: 75%;
  }
  .SPASample .col-lg-pull-8 {
    right: 66.66666667%;
  }
  .SPASample .col-lg-pull-7 {
    right: 58.33333333%;
  }
  .SPASample .col-lg-pull-6 {
    right: 50%;
  }
  .SPASample .col-lg-pull-5 {
    right: 41.66666667%;
  }
  .SPASample .col-lg-pull-4 {
    right: 33.33333333%;
  }
  .SPASample .col-lg-pull-3 {
    right: 25%;
  }
  .SPASample .col-lg-pull-2 {
    right: 16.66666667%;
  }
  .SPASample .col-lg-pull-1 {
    right: 8.33333333%;
  }
  .SPASample .col-lg-pull-0 {
    right: auto;
  }
  .SPASample .col-lg-push-12 {
    left: 100%;
  }
  .SPASample .col-lg-push-11 {
    left: 91.66666667%;
  }
  .SPASample .col-lg-push-10 {
    left: 83.33333333%;
  }
  .SPASample .col-lg-push-9 {
    left: 75%;
  }
  .SPASample .col-lg-push-8 {
    left: 66.66666667%;
  }
  .SPASample .col-lg-push-7 {
    left: 58.33333333%;
  }
  .SPASample .col-lg-push-6 {
    left: 50%;
  }
  .SPASample .col-lg-push-5 {
    left: 41.66666667%;
  }
  .SPASample .col-lg-push-4 {
    left: 33.33333333%;
  }
  .SPASample .col-lg-push-3 {
    left: 25%;
  }
  .SPASample .col-lg-push-2 {
    left: 16.66666667%;
  }
  .SPASample .col-lg-push-1 {
    left: 8.33333333%;
  }
  .SPASample .col-lg-push-0 {
    left: auto;
  }
  .SPASample .col-lg-offset-12 {
    margin-left: 100%;
  }
  .SPASample .col-lg-offset-11 {
    margin-left: 91.66666667%;
  }
  .SPASample .col-lg-offset-10 {
    margin-left: 83.33333333%;
  }
  .SPASample .col-lg-offset-9 {
    margin-left: 75%;
  }
  .SPASample .col-lg-offset-8 {
    margin-left: 66.66666667%;
  }
  .SPASample .col-lg-offset-7 {
    margin-left: 58.33333333%;
  }
  .SPASample .col-lg-offset-6 {
    margin-left: 50%;
  }
  .SPASample .col-lg-offset-5 {
    margin-left: 41.66666667%;
  }
  .SPASample .col-lg-offset-4 {
    margin-left: 33.33333333%;
  }
  .SPASample .col-lg-offset-3 {
    margin-left: 25%;
  }
  .SPASample .col-lg-offset-2 {
    margin-left: 16.66666667%;
  }
  .SPASample .col-lg-offset-1 {
    margin-left: 8.33333333%;
  }
  .SPASample .col-lg-offset-0 {
    margin-left: 0;
  }
}
.SPASample table {
  background-color: transparent;
}
.SPASample caption {
  padding-top: 8px;
  padding-bottom: 8px;
  color: #777;
  text-align: left;
}
.SPASample th {
  text-align: left;
}
.SPASample .table {
  width: 100%;
  max-width: 100%;
  margin-bottom: 20px;
}
.SPASample .table > thead > tr > th,
.SPASample .table > tbody > tr > th,
.SPASample .table > tfoot > tr > th,
.SPASample .table > thead > tr > td,
.SPASample .table > tbody > tr > td,
.SPASample .table > tfoot > tr > td {
  padding: 8px;
  line-height: 1.42857143;
  vertical-align: top;
  border-top: 1px solid #ddd;
}
.SPASample .table > thead > tr > th {
  vertical-align: bottom;
  border-bottom: 2px solid #ddd;
}
.SPASample .table > caption + thead > tr:first-child > th,
.SPASample .table > colgroup + thead > tr:first-child > th,
.SPASample .table > thead:first-child > tr:first-child > th,
.SPASample .table > caption + thead > tr:first-child > td,
.SPASample .table > colgroup + thead > tr:first-child > td,
.SPASample .table > thead:first-child > tr:first-child > td {
  border-top: 0;
}
.SPASample .table > tbody + tbody {
  border-top: 2px solid #ddd;
}
.SPASample .table .table {
  background-color: #fff;
}
.SPASample .table-condensed > thead > tr > th,
.SPASample .table-condensed > tbody > tr > th,
.SPASample .table-condensed > tfoot > tr > th,
.SPASample .table-condensed > thead > tr > td,
.SPASample .table-condensed > tbody > tr > td,
.SPASample .table-condensed > tfoot > tr > td {
  padding: 5px;
}
.SPASample .table-bordered {
  border: 1px solid #ddd;
}
.SPASample .table-bordered > thead > tr > th,
.SPASample .table-bordered > tbody > tr > th,
.SPASample .table-bordered > tfoot > tr > th,
.SPASample .table-bordered > thead > tr > td,
.SPASample .table-bordered > tbody > tr > td,
.SPASample .table-bordered > tfoot > tr > td {
  border: 1px solid #ddd;
}
.SPASample .table-bordered > thead > tr > th,
.SPASample .table-bordered > thead > tr > td {
  border-bottom-width: 2px;
}
.SPASample .table-striped > tbody > tr:nth-of-type(odd) {
  background-color: #f9f9f9;
}
.SPASample .table-hover > tbody > tr:hover {
  background-color: #f5f5f5;
}
.SPASample table col[class*="col-"] {
  position: static;
  display: table-column;
  float: none;
}
.SPASample table td[class*="col-"],
.SPASample table th[class*="col-"] {
  position: static;
  display: table-cell;
  float: none;
}
.SPASample .table > thead > tr > td.active,
.SPASample .table > tbody > tr > td.active,
.SPASample .table > tfoot > tr > td.active,
.SPASample .table > thead > tr > th.active,
.SPASample .table > tbody > tr > th.active,
.SPASample .table > tfoot > tr > th.active,
.SPASample .table > thead > tr.active > td,
.SPASample .table > tbody > tr.active > td,
.SPASample .table > tfoot > tr.active > td,
.SPASample .table > thead > tr.active > th,
.SPASample .table > tbody > tr.active > th,
.SPASample .table > tfoot > tr.active > th {
  background-color: #f5f5f5;
}
.SPASample .table-hover > tbody > tr > td.active:hover,
.SPASample .table-hover > tbody > tr > th.active:hover,
.SPASample .table-hover > tbody > tr.active:hover > td,
.SPASample .table-hover > tbody > tr:hover > .active,
.SPASample .table-hover > tbody > tr.active:hover > th {
  background-color: #e8e8e8;
}
.SPASample .table > thead > tr > td.success,
.SPASample .table > tbody > tr > td.success,
.SPASample .table > tfoot > tr > td.success,
.SPASample .table > thead > tr > th.success,
.SPASample .table > tbody > tr > th.success,
.SPASample .table > tfoot > tr > th.success,
.SPASample .table > thead > tr.success > td,
.SPASample .table > tbody > tr.success > td,
.SPASample .table > tfoot > tr.success > td,
.SPASample .table > thead > tr.success > th,
.SPASample .table > tbody > tr.success > th,
.SPASample .table > tfoot > tr.success > th {
  background-color: #dff0d8;
}
.SPASample .table-hover > tbody > tr > td.success:hover,
.SPASample .table-hover > tbody > tr > th.success:hover,
.SPASample .table-hover > tbody > tr.success:hover > td,
.SPASample .table-hover > tbody > tr:hover > .success,
.SPASample .table-hover > tbody > tr.success:hover > th {
  background-color: #d0e9c6;
}
.SPASample .table > thead > tr > td.info,
.SPASample .table > tbody > tr > td.info,
.SPASample .table > tfoot > tr > td.info,
.SPASample .table > thead > tr > th.info,
.SPASample .table > tbody > tr > th.info,
.SPASample .table > tfoot > tr > th.info,
.SPASample .table > thead > tr.info > td,
.SPASample .table > tbody > tr.info > td,
.SPASample .table > tfoot > tr.info > td,
.SPASample .table > thead > tr.info > th,
.SPASample .table > tbody > tr.info > th,
.SPASample .table > tfoot > tr.info > th {
  background-color: #d9edf7;
}
.SPASample .table-hover > tbody > tr > td.info:hover,
.SPASample .table-hover > tbody > tr > th.info:hover,
.SPASample .table-hover > tbody > tr.info:hover > td,
.SPASample .table-hover > tbody > tr:hover > .info,
.SPASample .table-hover > tbody > tr.info:hover > th {
  background-color: #c4e3f3;
}
.SPASample .table > thead > tr > td.warning,
.SPASample .table > tbody > tr > td.warning,
.SPASample .table > tfoot > tr > td.warning,
.SPASample .table > thead > tr > th.warning,
.SPASample .table > tbody > tr > th.warning,
.SPASample .table > tfoot > tr > th.warning,
.SPASample .table > thead > tr.warning > td,
.SPASample .table > tbody > tr.warning > td,
.SPASample .table > tfoot > tr.warning > td,
.SPASample .table > thead > tr.warning > th,
.SPASample .table > tbody > tr.warning > th,
.SPASample .table > tfoot > tr.warning > th {
  background-color: #fcf8e3;
}
.SPASample .table-hover > tbody > tr > td.warning:hover,
.SPASample .table-hover > tbody > tr > th.warning:hover,
.SPASample .table-hover > tbody > tr.warning:hover > td,
.SPASample .table-hover > tbody > tr:hover > .warning,
.SPASample .table-hover > tbody > tr.warning:hover > th {
  background-color: #faf2cc;
}
.SPASample .table > thead > tr > td.danger,
.SPASample .table > tbody > tr > td.danger,
.SPASample .table > tfoot > tr > td.danger,
.SPASample .table > thead > tr > th.danger,
.SPASample .table > tbody > tr > th.danger,
.SPASample .table > tfoot > tr > th.danger,
.SPASample .table > thead > tr.danger > td,
.SPASample .table > tbody > tr.danger > td,
.SPASample .table > tfoot > tr.danger > td,
.SPASample .table > thead > tr.danger > th,
.SPASample .table > tbody > tr.danger > th,
.SPASample .table > tfoot > tr.danger > th {
  background-color: #f2dede;
}
.SPASample .table-hover > tbody > tr > td.danger:hover,
.SPASample .table-hover > tbody > tr > th.danger:hover,
.SPASample .table-hover > tbody > tr.danger:hover > td,
.SPASample .table-hover > tbody > tr:hover > .danger,
.SPASample .table-hover > tbody > tr.danger:hover > th {
  background-color: #ebcccc;
}
.SPASample .table-responsive {
  min-height: .01%;
  overflow-x: auto;
}
@media screen and (max-width: 767px) {
  .SPASample .table-responsive {
    width: 100%;
    margin-bottom: 15px;
    overflow-y: hidden;
    -ms-overflow-style: -ms-autohiding-scrollbar;
    border: 1px solid #ddd;
  }
  .SPASample .table-responsive > .table {
    margin-bottom: 0;
  }
  .SPASample .table-responsive > .table > thead > tr > th,
  .SPASample .table-responsive > .table > tbody > tr > th,
  .SPASample .table-responsive > .table > tfoot > tr > th,
  .SPASample .table-responsive > .table > thead > tr > td,
  .SPASample .table-responsive > .table > tbody > tr > td,
  .SPASample .table-responsive > .table > tfoot > tr > td {
    white-space: nowrap;
  }
  .SPASample .table-responsive > .table-bordered {
    border: 0;
  }
  .SPASample .table-responsive > .table-bordered > thead > tr > th:first-child,
  .SPASample .table-responsive > .table-bordered > tbody > tr > th:first-child,
  .SPASample .table-responsive > .table-bordered > tfoot > tr > th:first-child,
  .SPASample .table-responsive > .table-bordered > thead > tr > td:first-child,
  .SPASample .table-responsive > .table-bordered > tbody > tr > td:first-child,
  .SPASample .table-responsive > .table-bordered > tfoot > tr > td:first-child {
    border-left: 0;
  }
  .SPASample .table-responsive > .table-bordered > thead > tr > th:last-child,
  .SPASample .table-responsive > .table-bordered > tbody > tr > th:last-child,
  .SPASample .table-responsive > .table-bordered > tfoot > tr > th:last-child,
  .SPASample .table-responsive > .table-bordered > thead > tr > td:last-child,
  .SPASample .table-responsive > .table-bordered > tbody > tr > td:last-child,
  .SPASample .table-responsive > .table-bordered > tfoot > tr > td:last-child {
    border-right: 0;
  }
  .SPASample .table-responsive > .table-bordered > tbody > tr:last-child > th,
  .SPASample .table-responsive > .table-bordered > tfoot > tr:last-child > th,
  .SPASample .table-responsive > .table-bordered > tbody > tr:last-child > td,
  .SPASample .table-responsive > .table-bordered > tfoot > tr:last-child > td {
    border-bottom: 0;
  }
}
.SPASample fieldset {
  min-width: 0;
  padding: 0;
  margin: 0;
  border: 0;
}
.SPASample legend {
  display: block;
  width: 100%;
  padding: 0;
  margin-bottom: 20px;
  font-size: 21px;
  line-height: inherit;
  color: #333;
  border: 0;
  border-bottom: 1px solid #e5e5e5;
}
.SPASample label {
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
  font-weight: bold;
}
.SPASample input[type="search"] {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
.SPASample input[type="radio"],
.SPASample input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
  line-height: normal;
}
.SPASample input[type="file"] {
  display: block;
}
.SPASample input[type="range"] {
  display: block;
  width: 100%;
}
.SPASample select[multiple],
.SPASample select[size] {
  height: auto;
}
.SPASample input[type="file"]:focus,
.SPASample input[type="radio"]:focus,
.SPASample input[type="checkbox"]:focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
.SPASample output {
  display: block;
  padding-top: 7px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
}
.SPASample .form-control {
  display: block;
  width: 100%;
  height: 34px;
  padding: 6px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  -webkit-transition: border-color ease-in-out 0.15s, -webkit-box-shadow ease-in-out 0.15s;
  -o-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
  transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}
.SPASample .form-control:focus {
  border-color: #66afe9;
  outline: 0;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(102, 175, 233, 0.6);
}
.SPASample .form-control::-moz-placeholder {
  color: #999;
  opacity: 1;
}
.SPASample .form-control:-ms-input-placeholder {
  color: #999;
}
.SPASample .form-control::-webkit-input-placeholder {
  color: #999;
}
.SPASample .form-control[disabled],
.SPASample .form-control[readonly],
.SPASample fieldset[disabled] .form-control {
  background-color: #eee;
  opacity: 1;
}
.SPASample .form-control[disabled],
.SPASample fieldset[disabled] .form-control {
  cursor: not-allowed;
}
.SPASample textarea.form-control {
  height: auto;
}
.SPASample input[type="search"] {
  -webkit-appearance: none;
}
@media screen and (-webkit-min-device-pixel-ratio: 0) {
  .SPASample input[type="date"],
  .SPASample input[type="time"],
  .SPASample input[type="datetime-local"],
  .SPASample input[type="month"] {
    line-height: 34px;
  }
  .SPASample input[type="date"].input-sm,
  .SPASample input[type="time"].input-sm,
  .SPASample input[type="datetime-local"].input-sm,
  .SPASample input[type="month"].input-sm,
  .SPASample .input-group-sm input[type="date"],
  .SPASample .input-group-sm input[type="time"],
  .SPASample .input-group-sm input[type="datetime-local"],
  .SPASample .input-group-sm input[type="month"] {
    line-height: 30px;
  }
  .SPASample input[type="date"].input-lg,
  .SPASample input[type="time"].input-lg,
  .SPASample input[type="datetime-local"].input-lg,
  .SPASample input[type="month"].input-lg,
  .SPASample .input-group-lg input[type="date"],
  .SPASample .input-group-lg input[type="time"],
  .SPASample .input-group-lg input[type="datetime-local"],
  .SPASample .input-group-lg input[type="month"] {
    line-height: 46px;
  }
}
.SPASample .form-group {
  margin-bottom: 15px;
}
.SPASample .radio,
.SPASample .checkbox {
  position: relative;
  display: block;
  margin-top: 10px;
  margin-bottom: 10px;
}
.SPASample .radio label,
.SPASample .checkbox label {
  min-height: 20px;
  padding-left: 20px;
  margin-bottom: 0;
  font-weight: normal;
  cursor: pointer;
}
.SPASample .radio input[type="radio"],
.SPASample .radio-inline input[type="radio"],
.SPASample .checkbox input[type="checkbox"],
.SPASample .checkbox-inline input[type="checkbox"] {
  position: absolute;
  margin-top: 4px \9;
  margin-left: -20px;
}
.SPASample .radio + .radio,
.SPASample .checkbox + .checkbox {
  margin-top: -5px;
}
.SPASample .radio-inline,
.SPASample .checkbox-inline {
  position: relative;
  display: inline-block;
  padding-left: 20px;
  margin-bottom: 0;
  font-weight: normal;
  vertical-align: middle;
  cursor: pointer;
}
.SPASample .radio-inline + .radio-inline,
.SPASample .checkbox-inline + .checkbox-inline {
  margin-top: 0;
  margin-left: 10px;
}
.SPASample input[type="radio"][disabled],
.SPASample input[type="checkbox"][disabled],
.SPASample input[type="radio"].disabled,
.SPASample input[type="checkbox"].disabled,
.SPASample fieldset[disabled] input[type="radio"],
.SPASample fieldset[disabled] input[type="checkbox"] {
  cursor: not-allowed;
}
.SPASample .radio-inline.disabled,
.SPASample .checkbox-inline.disabled,
.SPASample fieldset[disabled] .radio-inline,
.SPASample fieldset[disabled] .checkbox-inline {
  cursor: not-allowed;
}
.SPASample .radio.disabled label,
.SPASample .checkbox.disabled label,
.SPASample fieldset[disabled] .radio label,
.SPASample fieldset[disabled] .checkbox label {
  cursor: not-allowed;
}
.SPASample .form-control-static {
  min-height: 34px;
  padding-top: 7px;
  padding-bottom: 7px;
  margin-bottom: 0;
}
.SPASample .form-control-static.input-lg,
.SPASample .form-control-static.input-sm {
  padding-right: 0;
  padding-left: 0;
}
.SPASample .input-sm {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
.SPASample select.input-sm {
  height: 30px;
  line-height: 30px;
}
.SPASample textarea.input-sm,
.SPASample select[multiple].input-sm {
  height: auto;
}
.SPASample .form-group-sm .form-control {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
.SPASample select.form-group-sm .form-control {
  height: 30px;
  line-height: 30px;
}
.SPASample textarea.form-group-sm .form-control,
.SPASample select[multiple].form-group-sm .form-control {
  height: auto;
}
.SPASample .form-group-sm .form-control-static {
  height: 30px;
  min-height: 32px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
}
.SPASample .input-lg {
  height: 46px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.3333333;
  border-radius: 6px;
}
.SPASample select.input-lg {
  height: 46px;
  line-height: 46px;
}
.SPASample textarea.input-lg,
.SPASample select[multiple].input-lg {
  height: auto;
}
.SPASample .form-group-lg .form-control {
  height: 46px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.3333333;
  border-radius: 6px;
}
.SPASample select.form-group-lg .form-control {
  height: 46px;
  line-height: 46px;
}
.SPASample textarea.form-group-lg .form-control,
.SPASample select[multiple].form-group-lg .form-control {
  height: auto;
}
.SPASample .form-group-lg .form-control-static {
  height: 46px;
  min-height: 38px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.3333333;
}
.SPASample .has-feedback {
  position: relative;
}
.SPASample .has-feedback .form-control {
  padding-right: 42.5px;
}
.SPASample .form-control-feedback {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 2;
  display: block;
  width: 34px;
  height: 34px;
  line-height: 34px;
  text-align: center;
  pointer-events: none;
}
.SPASample .input-lg + .form-control-feedback {
  width: 46px;
  height: 46px;
  line-height: 46px;
}
.SPASample .input-sm + .form-control-feedback {
  width: 30px;
  height: 30px;
  line-height: 30px;
}
.SPASample .has-success .help-block,
.SPASample .has-success .control-label,
.SPASample .has-success .radio,
.SPASample .has-success .checkbox,
.SPASample .has-success .radio-inline,
.SPASample .has-success .checkbox-inline,
.SPASample .has-success.radio label,
.SPASample .has-success.checkbox label,
.SPASample .has-success.radio-inline label,
.SPASample .has-success.checkbox-inline label {
  color: #3c763d;
}
.SPASample .has-success .form-control {
  border-color: #3c763d;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
.SPASample .has-success .form-control:focus {
  border-color: #2b542c;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #67b168;
}
.SPASample .has-success .input-group-addon {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #3c763d;
}
.SPASample .has-success .form-control-feedback {
  color: #3c763d;
}
.SPASample .has-warning .help-block,
.SPASample .has-warning .control-label,
.SPASample .has-warning .radio,
.SPASample .has-warning .checkbox,
.SPASample .has-warning .radio-inline,
.SPASample .has-warning .checkbox-inline,
.SPASample .has-warning.radio label,
.SPASample .has-warning.checkbox label,
.SPASample .has-warning.radio-inline label,
.SPASample .has-warning.checkbox-inline label {
  color: #8a6d3b;
}
.SPASample .has-warning .form-control {
  border-color: #8a6d3b;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
.SPASample .has-warning .form-control:focus {
  border-color: #66512c;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c0a16b;
}
.SPASample .has-warning .input-group-addon {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #8a6d3b;
}
.SPASample .has-warning .form-control-feedback {
  color: #8a6d3b;
}
.SPASample .has-error .help-block,
.SPASample .has-error .control-label,
.SPASample .has-error .radio,
.SPASample .has-error .checkbox,
.SPASample .has-error .radio-inline,
.SPASample .has-error .checkbox-inline,
.SPASample .has-error.radio label,
.SPASample .has-error.checkbox label,
.SPASample .has-error.radio-inline label,
.SPASample .has-error.checkbox-inline label {
  color: #a94442;
}
.SPASample .has-error .form-control {
  border-color: #a94442;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
.SPASample .has-error .form-control:focus {
  border-color: #843534;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #ce8483;
}
.SPASample .has-error .input-group-addon {
  color: #a94442;
  background-color: #f2dede;
  border-color: #a94442;
}
.SPASample .has-error .form-control-feedback {
  color: #a94442;
}
.SPASample .has-feedback label ~ .form-control-feedback {
  top: 25px;
}
.SPASample .has-feedback label.sr-only ~ .form-control-feedback {
  top: 0;
}
.SPASample .help-block {
  display: block;
  margin-top: 5px;
  margin-bottom: 10px;
  color: #737373;
}
@media (min-width: 768px) {
  .SPASample .form-inline .form-group {
    display: inline-block;
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .form-inline .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
  }
  .SPASample .form-inline .form-control-static {
    display: inline-block;
  }
  .SPASample .form-inline .input-group {
    display: inline-table;
    vertical-align: middle;
  }
  .SPASample .form-inline .input-group .input-group-addon,
  .SPASample .form-inline .input-group .input-group-btn,
  .SPASample .form-inline .input-group .form-control {
    width: auto;
  }
  .SPASample .form-inline .input-group > .form-control {
    width: 100%;
  }
  .SPASample .form-inline .control-label {
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .form-inline .radio,
  .SPASample .form-inline .checkbox {
    display: inline-block;
    margin-top: 0;
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .form-inline .radio label,
  .SPASample .form-inline .checkbox label {
    padding-left: 0;
  }
  .SPASample .form-inline .radio input[type="radio"],
  .SPASample .form-inline .checkbox input[type="checkbox"] {
    position: relative;
    margin-left: 0;
  }
  .SPASample .form-inline .has-feedback .form-control-feedback {
    top: 0;
  }
}
.SPASample .form-horizontal .radio,
.SPASample .form-horizontal .checkbox,
.SPASample .form-horizontal .radio-inline,
.SPASample .form-horizontal .checkbox-inline {
  padding-top: 7px;
  margin-top: 0;
  margin-bottom: 0;
}
.SPASample .form-horizontal .radio,
.SPASample .form-horizontal .checkbox {
  min-height: 27px;
}
.SPASample .form-horizontal .form-group {
  margin-right: -15px;
  margin-left: -15px;
}
@media (min-width: 768px) {
  .SPASample .form-horizontal .control-label {
    padding-top: 7px;
    margin-bottom: 0;
    text-align: right;
  }
}
.SPASample .form-horizontal .has-feedback .form-control-feedback {
  right: 15px;
}
@media (min-width: 768px) {
  .SPASample .form-horizontal .form-group-lg .control-label {
    padding-top: 14.333333px;
  }
}
@media (min-width: 768px) {
  .SPASample .form-horizontal .form-group-sm .control-label {
    padding-top: 6px;
  }
}
.SPASample .btn {
  display: inline-block;
  padding: 6px 12px;
  margin-bottom: 0;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857143;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -ms-touch-action: manipulation;
  touch-action: manipulation;
  cursor: pointer;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}
.SPASample .btn:focus,
.SPASample .btn:active:focus,
.SPASample .btn.active:focus,
.SPASample .btn.focus,
.SPASample .btn:active.focus,
.SPASample .btn.active.focus {
  outline: thin dotted;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}
.SPASample .btn:hover,
.SPASample .btn:focus,
.SPASample .btn.focus {
  color: #333;
  text-decoration: none;
}
.SPASample .btn:active,
.SPASample .btn.active {
  background-image: none;
  outline: 0;
  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
.SPASample .btn.disabled,
.SPASample .btn[disabled],
.SPASample fieldset[disabled] .btn {
  pointer-events: none;
  cursor: not-allowed;
  filter: alpha(opacity=65);
  -webkit-box-shadow: none;
  box-shadow: none;
  opacity: .65;
}
.SPASample .btn-default {
  color: #333;
  background-color: #fff;
  border-color: #ccc;
}
.SPASample .btn-default:hover,
.SPASample .btn-default:focus,
.SPASample .btn-default.focus,
.SPASample .btn-default:active,
.SPASample .btn-default.active,
.SPASample .open > .dropdown-toggle.btn-default {
  color: #333;
  background-color: #e6e6e6;
  border-color: #adadad;
}
.SPASample .btn-default:active,
.SPASample .btn-default.active,
.SPASample .open > .dropdown-toggle.btn-default {
  background-image: none;
}
.SPASample .btn-default.disabled,
.SPASample .btn-default[disabled],
.SPASample fieldset[disabled] .btn-default,
.SPASample .btn-default.disabled:hover,
.SPASample .btn-default[disabled]:hover,
.SPASample fieldset[disabled] .btn-default:hover,
.SPASample .btn-default.disabled:focus,
.SPASample .btn-default[disabled]:focus,
.SPASample fieldset[disabled] .btn-default:focus,
.SPASample .btn-default.disabled.focus,
.SPASample .btn-default[disabled].focus,
.SPASample fieldset[disabled] .btn-default.focus,
.SPASample .btn-default.disabled:active,
.SPASample .btn-default[disabled]:active,
.SPASample fieldset[disabled] .btn-default:active,
.SPASample .btn-default.disabled.active,
.SPASample .btn-default[disabled].active,
.SPASample fieldset[disabled] .btn-default.active {
  background-color: #fff;
  border-color: #ccc;
}
.SPASample .btn-default .badge {
  color: #fff;
  background-color: #333;
}
.SPASample .btn-primary {
  color: #fff;
  background-color: #337ab7;
  border-color: #2e6da4;
}
.SPASample .btn-primary:hover,
.SPASample .btn-primary:focus,
.SPASample .btn-primary.focus,
.SPASample .btn-primary:active,
.SPASample .btn-primary.active,
.SPASample .open > .dropdown-toggle.btn-primary {
  color: #fff;
  background-color: #286090;
  border-color: #204d74;
}
.SPASample .btn-primary:active,
.SPASample .btn-primary.active,
.SPASample .open > .dropdown-toggle.btn-primary {
  background-image: none;
}
.SPASample .btn-primary.disabled,
.SPASample .btn-primary[disabled],
.SPASample fieldset[disabled] .btn-primary,
.SPASample .btn-primary.disabled:hover,
.SPASample .btn-primary[disabled]:hover,
.SPASample fieldset[disabled] .btn-primary:hover,
.SPASample .btn-primary.disabled:focus,
.SPASample .btn-primary[disabled]:focus,
.SPASample fieldset[disabled] .btn-primary:focus,
.SPASample .btn-primary.disabled.focus,
.SPASample .btn-primary[disabled].focus,
.SPASample fieldset[disabled] .btn-primary.focus,
.SPASample .btn-primary.disabled:active,
.SPASample .btn-primary[disabled]:active,
.SPASample fieldset[disabled] .btn-primary:active,
.SPASample .btn-primary.disabled.active,
.SPASample .btn-primary[disabled].active,
.SPASample fieldset[disabled] .btn-primary.active {
  background-color: #337ab7;
  border-color: #2e6da4;
}
.SPASample .btn-primary .badge {
  color: #337ab7;
  background-color: #fff;
}
.SPASample .btn-success {
  color: #fff;
  background-color: #5cb85c;
  border-color: #4cae4c;
}
.SPASample .btn-success:hover,
.SPASample .btn-success:focus,
.SPASample .btn-success.focus,
.SPASample .btn-success:active,
.SPASample .btn-success.active,
.SPASample .open > .dropdown-toggle.btn-success {
  color: #fff;
  background-color: #449d44;
  border-color: #398439;
}
.SPASample .btn-success:active,
.SPASample .btn-success.active,
.SPASample .open > .dropdown-toggle.btn-success {
  background-image: none;
}
.SPASample .btn-success.disabled,
.SPASample .btn-success[disabled],
.SPASample fieldset[disabled] .btn-success,
.SPASample .btn-success.disabled:hover,
.SPASample .btn-success[disabled]:hover,
.SPASample fieldset[disabled] .btn-success:hover,
.SPASample .btn-success.disabled:focus,
.SPASample .btn-success[disabled]:focus,
.SPASample fieldset[disabled] .btn-success:focus,
.SPASample .btn-success.disabled.focus,
.SPASample .btn-success[disabled].focus,
.SPASample fieldset[disabled] .btn-success.focus,
.SPASample .btn-success.disabled:active,
.SPASample .btn-success[disabled]:active,
.SPASample fieldset[disabled] .btn-success:active,
.SPASample .btn-success.disabled.active,
.SPASample .btn-success[disabled].active,
.SPASample fieldset[disabled] .btn-success.active {
  background-color: #5cb85c;
  border-color: #4cae4c;
}
.SPASample .btn-success .badge {
  color: #5cb85c;
  background-color: #fff;
}
.SPASample .btn-info {
  color: #fff;
  background-color: #5bc0de;
  border-color: #46b8da;
}
.SPASample .btn-info:hover,
.SPASample .btn-info:focus,
.SPASample .btn-info.focus,
.SPASample .btn-info:active,
.SPASample .btn-info.active,
.SPASample .open > .dropdown-toggle.btn-info {
  color: #fff;
  background-color: #31b0d5;
  border-color: #269abc;
}
.SPASample .btn-info:active,
.SPASample .btn-info.active,
.SPASample .open > .dropdown-toggle.btn-info {
  background-image: none;
}
.SPASample .btn-info.disabled,
.SPASample .btn-info[disabled],
.SPASample fieldset[disabled] .btn-info,
.SPASample .btn-info.disabled:hover,
.SPASample .btn-info[disabled]:hover,
.SPASample fieldset[disabled] .btn-info:hover,
.SPASample .btn-info.disabled:focus,
.SPASample .btn-info[disabled]:focus,
.SPASample fieldset[disabled] .btn-info:focus,
.SPASample .btn-info.disabled.focus,
.SPASample .btn-info[disabled].focus,
.SPASample fieldset[disabled] .btn-info.focus,
.SPASample .btn-info.disabled:active,
.SPASample .btn-info[disabled]:active,
.SPASample fieldset[disabled] .btn-info:active,
.SPASample .btn-info.disabled.active,
.SPASample .btn-info[disabled].active,
.SPASample fieldset[disabled] .btn-info.active {
  background-color: #5bc0de;
  border-color: #46b8da;
}
.SPASample .btn-info .badge {
  color: #5bc0de;
  background-color: #fff;
}
.SPASample .btn-warning {
  color: #fff;
  background-color: #f0ad4e;
  border-color: #eea236;
}
.SPASample .btn-warning:hover,
.SPASample .btn-warning:focus,
.SPASample .btn-warning.focus,
.SPASample .btn-warning:active,
.SPASample .btn-warning.active,
.SPASample .open > .dropdown-toggle.btn-warning {
  color: #fff;
  background-color: #ec971f;
  border-color: #d58512;
}
.SPASample .btn-warning:active,
.SPASample .btn-warning.active,
.SPASample .open > .dropdown-toggle.btn-warning {
  background-image: none;
}
.SPASample .btn-warning.disabled,
.SPASample .btn-warning[disabled],
.SPASample fieldset[disabled] .btn-warning,
.SPASample .btn-warning.disabled:hover,
.SPASample .btn-warning[disabled]:hover,
.SPASample fieldset[disabled] .btn-warning:hover,
.SPASample .btn-warning.disabled:focus,
.SPASample .btn-warning[disabled]:focus,
.SPASample fieldset[disabled] .btn-warning:focus,
.SPASample .btn-warning.disabled.focus,
.SPASample .btn-warning[disabled].focus,
.SPASample fieldset[disabled] .btn-warning.focus,
.SPASample .btn-warning.disabled:active,
.SPASample .btn-warning[disabled]:active,
.SPASample fieldset[disabled] .btn-warning:active,
.SPASample .btn-warning.disabled.active,
.SPASample .btn-warning[disabled].active,
.SPASample fieldset[disabled] .btn-warning.active {
  background-color: #f0ad4e;
  border-color: #eea236;
}
.SPASample .btn-warning .badge {
  color: #f0ad4e;
  background-color: #fff;
}
.SPASample .btn-danger {
  color: #fff;
  background-color: #d9534f;
  border-color: #d43f3a;
}
.SPASample .btn-danger:hover,
.SPASample .btn-danger:focus,
.SPASample .btn-danger.focus,
.SPASample .btn-danger:active,
.SPASample .btn-danger.active,
.SPASample .open > .dropdown-toggle.btn-danger {
  color: #fff;
  background-color: #c9302c;
  border-color: #ac2925;
}
.SPASample .btn-danger:active,
.SPASample .btn-danger.active,
.SPASample .open > .dropdown-toggle.btn-danger {
  background-image: none;
}
.SPASample .btn-danger.disabled,
.SPASample .btn-danger[disabled],
.SPASample fieldset[disabled] .btn-danger,
.SPASample .btn-danger.disabled:hover,
.SPASample .btn-danger[disabled]:hover,
.SPASample fieldset[disabled] .btn-danger:hover,
.SPASample .btn-danger.disabled:focus,
.SPASample .btn-danger[disabled]:focus,
.SPASample fieldset[disabled] .btn-danger:focus,
.SPASample .btn-danger.disabled.focus,
.SPASample .btn-danger[disabled].focus,
.SPASample fieldset[disabled] .btn-danger.focus,
.SPASample .btn-danger.disabled:active,
.SPASample .btn-danger[disabled]:active,
.SPASample fieldset[disabled] .btn-danger:active,
.SPASample .btn-danger.disabled.active,
.SPASample .btn-danger[disabled].active,
.SPASample fieldset[disabled] .btn-danger.active {
  background-color: #d9534f;
  border-color: #d43f3a;
}
.SPASample .btn-danger .badge {
  color: #d9534f;
  background-color: #fff;
}
.SPASample .btn-link {
  font-weight: normal;
  color: #337ab7;
  border-radius: 0;
}
.SPASample .btn-link,
.SPASample .btn-link:active,
.SPASample .btn-link.active,
.SPASample .btn-link[disabled],
.SPASample fieldset[disabled] .btn-link {
  background-color: transparent;
  -webkit-box-shadow: none;
  box-shadow: none;
}
.SPASample .btn-link,
.SPASample .btn-link:hover,
.SPASample .btn-link:focus,
.SPASample .btn-link:active {
  border-color: transparent;
}
.SPASample .btn-link:hover,
.SPASample .btn-link:focus {
  color: #23527c;
  text-decoration: underline;
  background-color: transparent;
}
.SPASample .btn-link[disabled]:hover,
.SPASample fieldset[disabled] .btn-link:hover,
.SPASample .btn-link[disabled]:focus,
.SPASample fieldset[disabled] .btn-link:focus {
  color: #777;
  text-decoration: none;
}
.SPASample .btn-lg,
.SPASample .btn-group-lg > .btn {
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.3333333;
  border-radius: 6px;
}
.SPASample .btn-sm,
.SPASample .btn-group-sm > .btn {
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
.SPASample .btn-xs,
.SPASample .btn-group-xs > .btn {
  padding: 1px 5px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
.SPASample .btn-block {
  display: block;
  width: 100%;
}
.SPASample .btn-block + .btn-block {
  margin-top: 5px;
}
.SPASample input[type="submit"].btn-block,
.SPASample input[type="reset"].btn-block,
.SPASample input[type="button"].btn-block {
  width: 100%;
}
.SPASample .fade {
  opacity: 0;
  -webkit-transition: opacity .15s linear;
  -o-transition: opacity .15s linear;
  transition: opacity .15s linear;
}
.SPASample .fade.in {
  opacity: 1;
}
.SPASample .collapse {
  display: none;
}
.SPASample .collapse.in {
  display: block;
}
.SPASample tr.collapse.in {
  display: table-row;
}
.SPASample tbody.collapse.in {
  display: table-row-group;
}
.SPASample .collapsing {
  position: relative;
  height: 0;
  overflow: hidden;
  -webkit-transition-timing-function: ease;
  -o-transition-timing-function: ease;
  transition-timing-function: ease;
  -webkit-transition-duration: .35s;
  -o-transition-duration: .35s;
  transition-duration: .35s;
  -webkit-transition-property: height, visibility;
  -o-transition-property: height, visibility;
  transition-property: height, visibility;
}
.SPASample .caret {
  display: inline-block;
  width: 0;
  height: 0;
  margin-left: 2px;
  vertical-align: middle;
  border-top: 4px dashed;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
}
.SPASample .dropup,
.SPASample .dropdown {
  position: relative;
}
.SPASample .dropdown-toggle:focus {
  outline: 0;
}
.SPASample .dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 5px 0;
  margin: 2px 0 0;
  font-size: 14px;
  text-align: left;
  list-style: none;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  border-radius: 4px;
  -webkit-box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.175);
}
.SPASample .dropdown-menu.pull-right {
  right: 0;
  left: auto;
}
.SPASample .dropdown-menu .divider {
  height: 1px;
  margin: 9px 0;
  overflow: hidden;
  background-color: #e5e5e5;
}
.SPASample .dropdown-menu > li > a {
  display: block;
  padding: 3px 20px;
  clear: both;
  font-weight: normal;
  line-height: 1.42857143;
  color: #333;
  white-space: nowrap;
}
.SPASample .dropdown-menu > li > a:hover,
.SPASample .dropdown-menu > li > a:focus {
  color: #262626;
  text-decoration: none;
  background-color: #f5f5f5;
}
.SPASample .dropdown-menu > .active > a,
.SPASample .dropdown-menu > .active > a:hover,
.SPASample .dropdown-menu > .active > a:focus {
  color: #fff;
  text-decoration: none;
  background-color: #337ab7;
  outline: 0;
}
.SPASample .dropdown-menu > .disabled > a,
.SPASample .dropdown-menu > .disabled > a:hover,
.SPASample .dropdown-menu > .disabled > a:focus {
  color: #777;
}
.SPASample .dropdown-menu > .disabled > a:hover,
.SPASample .dropdown-menu > .disabled > a:focus {
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
  background-image: none;
  filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
}
.SPASample .open > .dropdown-menu {
  display: block;
}
.SPASample .open > a {
  outline: 0;
}
.SPASample .dropdown-menu-right {
  right: 0;
  left: auto;
}
.SPASample .dropdown-menu-left {
  right: auto;
  left: 0;
}
.SPASample .dropdown-header {
  display: block;
  padding: 3px 20px;
  font-size: 12px;
  line-height: 1.42857143;
  color: #777;
  white-space: nowrap;
}
.SPASample .dropdown-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 990;
}
.SPASample .pull-right > .dropdown-menu {
  right: 0;
  left: auto;
}
.SPASample .dropup .caret,
.SPASample .navbar-fixed-bottom .dropdown .caret {
  content: "";
  border-top: 0;
  border-bottom: 4px solid;
}
.SPASample .dropup .dropdown-menu,
.SPASample .navbar-fixed-bottom .dropdown .dropdown-menu {
  top: auto;
  bottom: 100%;
  margin-bottom: 2px;
}
@media (min-width: 768px) {
  .SPASample .navbar-right .dropdown-menu {
    right: 0;
    left: auto;
  }
  .SPASample .navbar-right .dropdown-menu-left {
    right: auto;
    left: 0;
  }
}
.SPASample .btn-group,
.SPASample .btn-group-vertical {
  position: relative;
  display: inline-block;
  vertical-align: middle;
}
.SPASample .btn-group > .btn,
.SPASample .btn-group-vertical > .btn {
  position: relative;
  float: left;
}
.SPASample .btn-group > .btn:hover,
.SPASample .btn-group-vertical > .btn:hover,
.SPASample .btn-group > .btn:focus,
.SPASample .btn-group-vertical > .btn:focus,
.SPASample .btn-group > .btn:active,
.SPASample .btn-group-vertical > .btn:active,
.SPASample .btn-group > .btn.active,
.SPASample .btn-group-vertical > .btn.active {
  z-index: 2;
}
.SPASample .btn-group .btn + .btn,
.SPASample .btn-group .btn + .btn-group,
.SPASample .btn-group .btn-group + .btn,
.SPASample .btn-group .btn-group + .btn-group {
  margin-left: -1px;
}
.SPASample .btn-toolbar {
  margin-left: -5px;
}
.SPASample .btn-toolbar .btn-group,
.SPASample .btn-toolbar .input-group {
  float: left;
}
.SPASample .btn-toolbar > .btn,
.SPASample .btn-toolbar > .btn-group,
.SPASample .btn-toolbar > .input-group {
  margin-left: 5px;
}
.SPASample .btn-group > .btn:not(:first-child):not(:last-child):not(.dropdown-toggle) {
  border-radius: 0;
}
.SPASample .btn-group > .btn:first-child {
  margin-left: 0;
}
.SPASample .btn-group > .btn:first-child:not(:last-child):not(.dropdown-toggle) {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.SPASample .btn-group > .btn:last-child:not(:first-child),
.SPASample .btn-group > .dropdown-toggle:not(:first-child) {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .btn-group > .btn-group {
  float: left;
}
.SPASample .btn-group > .btn-group:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
.SPASample .btn-group > .btn-group:first-child:not(:last-child) > .btn:last-child,
.SPASample .btn-group > .btn-group:first-child:not(:last-child) > .dropdown-toggle {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.SPASample .btn-group > .btn-group:last-child:not(:first-child) > .btn:first-child {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .btn-group .dropdown-toggle:active,
.SPASample .btn-group.open .dropdown-toggle {
  outline: 0;
}
.SPASample .btn-group > .btn + .dropdown-toggle {
  padding-right: 8px;
  padding-left: 8px;
}
.SPASample .btn-group > .btn-lg + .dropdown-toggle {
  padding-right: 12px;
  padding-left: 12px;
}
.SPASample .btn-group.open .dropdown-toggle {
  -webkit-box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
  box-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
}
.SPASample .btn-group.open .dropdown-toggle.btn-link {
  -webkit-box-shadow: none;
  box-shadow: none;
}
.SPASample .btn .caret {
  margin-left: 0;
}
.SPASample .btn-lg .caret {
  border-width: 5px 5px 0;
  border-bottom-width: 0;
}
.SPASample .dropup .btn-lg .caret {
  border-width: 0 5px 5px;
}
.SPASample .btn-group-vertical > .btn,
.SPASample .btn-group-vertical > .btn-group,
.SPASample .btn-group-vertical > .btn-group > .btn {
  display: block;
  float: none;
  width: 100%;
  max-width: 100%;
}
.SPASample .btn-group-vertical > .btn-group > .btn {
  float: none;
}
.SPASample .btn-group-vertical > .btn + .btn,
.SPASample .btn-group-vertical > .btn + .btn-group,
.SPASample .btn-group-vertical > .btn-group + .btn,
.SPASample .btn-group-vertical > .btn-group + .btn-group {
  margin-top: -1px;
  margin-left: 0;
}
.SPASample .btn-group-vertical > .btn:not(:first-child):not(:last-child) {
  border-radius: 0;
}
.SPASample .btn-group-vertical > .btn:first-child:not(:last-child) {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .btn-group-vertical > .btn:last-child:not(:first-child) {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
  border-bottom-left-radius: 4px;
}
.SPASample .btn-group-vertical > .btn-group:not(:first-child):not(:last-child) > .btn {
  border-radius: 0;
}
.SPASample .btn-group-vertical > .btn-group:first-child:not(:last-child) > .btn:last-child,
.SPASample .btn-group-vertical > .btn-group:first-child:not(:last-child) > .dropdown-toggle {
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .btn-group-vertical > .btn-group:last-child:not(:first-child) > .btn:first-child {
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.SPASample .btn-group-justified {
  display: table;
  width: 100%;
  table-layout: fixed;
  border-collapse: separate;
}
.SPASample .btn-group-justified > .btn,
.SPASample .btn-group-justified > .btn-group {
  display: table-cell;
  float: none;
  width: 1%;
}
.SPASample .btn-group-justified > .btn-group .btn {
  width: 100%;
}
.SPASample .btn-group-justified > .btn-group .dropdown-menu {
  left: auto;
}
.SPASample [data-toggle="buttons"] > .btn input[type="radio"],
.SPASample [data-toggle="buttons"] > .btn-group > .btn input[type="radio"],
.SPASample [data-toggle="buttons"] > .btn input[type="checkbox"],
.SPASample [data-toggle="buttons"] > .btn-group > .btn input[type="checkbox"] {
  position: absolute;
  clip: rect(0, 0, 0, 0);
  pointer-events: none;
}
.SPASample .input-group {
  position: relative;
  display: table;
  border-collapse: separate;
}
.SPASample .input-group[class*="col-"] {
  float: none;
  padding-right: 0;
  padding-left: 0;
}
.SPASample .input-group .form-control {
  position: relative;
  z-index: 2;
  float: left;
  width: 100%;
  margin-bottom: 0;
}
.SPASample .input-group-lg > .form-control,
.SPASample .input-group-lg > .input-group-addon,
.SPASample .input-group-lg > .input-group-btn > .btn {
  height: 46px;
  padding: 10px 16px;
  font-size: 18px;
  line-height: 1.3333333;
  border-radius: 6px;
}
.SPASample select.input-group-lg > .form-control,
.SPASample select.input-group-lg > .input-group-addon,
.SPASample select.input-group-lg > .input-group-btn > .btn {
  height: 46px;
  line-height: 46px;
}
.SPASample textarea.input-group-lg > .form-control,
.SPASample textarea.input-group-lg > .input-group-addon,
.SPASample textarea.input-group-lg > .input-group-btn > .btn,
.SPASample select[multiple].input-group-lg > .form-control,
.SPASample select[multiple].input-group-lg > .input-group-addon,
.SPASample select[multiple].input-group-lg > .input-group-btn > .btn {
  height: auto;
}
.SPASample .input-group-sm > .form-control,
.SPASample .input-group-sm > .input-group-addon,
.SPASample .input-group-sm > .input-group-btn > .btn {
  height: 30px;
  padding: 5px 10px;
  font-size: 12px;
  line-height: 1.5;
  border-radius: 3px;
}
.SPASample select.input-group-sm > .form-control,
.SPASample select.input-group-sm > .input-group-addon,
.SPASample select.input-group-sm > .input-group-btn > .btn {
  height: 30px;
  line-height: 30px;
}
.SPASample textarea.input-group-sm > .form-control,
.SPASample textarea.input-group-sm > .input-group-addon,
.SPASample textarea.input-group-sm > .input-group-btn > .btn,
.SPASample select[multiple].input-group-sm > .form-control,
.SPASample select[multiple].input-group-sm > .input-group-addon,
.SPASample select[multiple].input-group-sm > .input-group-btn > .btn {
  height: auto;
}
.SPASample .input-group-addon,
.SPASample .input-group-btn,
.SPASample .input-group .form-control {
  display: table-cell;
}
.SPASample .input-group-addon:not(:first-child):not(:last-child),
.SPASample .input-group-btn:not(:first-child):not(:last-child),
.SPASample .input-group .form-control:not(:first-child):not(:last-child) {
  border-radius: 0;
}
.SPASample .input-group-addon,
.SPASample .input-group-btn {
  width: 1%;
  white-space: nowrap;
  vertical-align: middle;
}
.SPASample .input-group-addon {
  padding: 6px 12px;
  font-size: 14px;
  font-weight: normal;
  line-height: 1;
  color: #555;
  text-align: center;
  background-color: #eee;
  border: 1px solid #ccc;
  border-radius: 4px;
}
.SPASample .input-group-addon.input-sm {
  padding: 5px 10px;
  font-size: 12px;
  border-radius: 3px;
}
.SPASample .input-group-addon.input-lg {
  padding: 10px 16px;
  font-size: 18px;
  border-radius: 6px;
}
.SPASample .input-group-addon input[type="radio"],
.SPASample .input-group-addon input[type="checkbox"] {
  margin-top: 0;
}
.SPASample .input-group .form-control:first-child,
.SPASample .input-group-addon:first-child,
.SPASample .input-group-btn:first-child > .btn,
.SPASample .input-group-btn:first-child > .btn-group > .btn,
.SPASample .input-group-btn:first-child > .dropdown-toggle,
.SPASample .input-group-btn:last-child > .btn:not(:last-child):not(.dropdown-toggle),
.SPASample .input-group-btn:last-child > .btn-group:not(:last-child) > .btn {
  border-top-right-radius: 0;
  border-bottom-right-radius: 0;
}
.SPASample .input-group-addon:first-child {
  border-right: 0;
}
.SPASample .input-group .form-control:last-child,
.SPASample .input-group-addon:last-child,
.SPASample .input-group-btn:last-child > .btn,
.SPASample .input-group-btn:last-child > .btn-group > .btn,
.SPASample .input-group-btn:last-child > .dropdown-toggle,
.SPASample .input-group-btn:first-child > .btn:not(:first-child),
.SPASample .input-group-btn:first-child > .btn-group:not(:first-child) > .btn {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .input-group-addon:last-child {
  border-left: 0;
}
.SPASample .input-group-btn {
  position: relative;
  font-size: 0;
  white-space: nowrap;
}
.SPASample .input-group-btn > .btn {
  position: relative;
}
.SPASample .input-group-btn > .btn + .btn {
  margin-left: -1px;
}
.SPASample .input-group-btn > .btn:hover,
.SPASample .input-group-btn > .btn:focus,
.SPASample .input-group-btn > .btn:active {
  z-index: 2;
}
.SPASample .input-group-btn:first-child > .btn,
.SPASample .input-group-btn:first-child > .btn-group {
  margin-right: -1px;
}
.SPASample .input-group-btn:last-child > .btn,
.SPASample .input-group-btn:last-child > .btn-group {
  margin-left: -1px;
}
.SPASample .nav {
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
.SPASample .nav > li {
  position: relative;
  display: block;
}
.SPASample .nav > li > a {
  position: relative;
  display: block;
  padding: 10px 15px;
}
.SPASample .nav > li > a:hover,
.SPASample .nav > li > a:focus {
  text-decoration: none;
  background-color: #eee;
}
.SPASample .nav > li.disabled > a {
  color: #777;
}
.SPASample .nav > li.disabled > a:hover,
.SPASample .nav > li.disabled > a:focus {
  color: #777;
  text-decoration: none;
  cursor: not-allowed;
  background-color: transparent;
}
.SPASample .nav .open > a,
.SPASample .nav .open > a:hover,
.SPASample .nav .open > a:focus {
  background-color: #eee;
  border-color: #337ab7;
}
.SPASample .nav .nav-divider {
  height: 1px;
  margin: 9px 0;
  overflow: hidden;
  background-color: #e5e5e5;
}
.SPASample .nav > li > a > img {
  max-width: none;
}
.SPASample .nav-tabs {
  border-bottom: 1px solid #ddd;
}
.SPASample .nav-tabs > li {
  float: left;
  margin-bottom: -1px;
}
.SPASample .nav-tabs > li > a {
  margin-right: 2px;
  line-height: 1.42857143;
  border: 1px solid transparent;
  border-radius: 4px 4px 0 0;
}
.SPASample .nav-tabs > li > a:hover {
  border-color: #eee #eee #ddd;
}
.SPASample .nav-tabs > li.active > a,
.SPASample .nav-tabs > li.active > a:hover,
.SPASample .nav-tabs > li.active > a:focus {
  color: #555;
  cursor: default;
  background-color: #fff;
  border: 1px solid #ddd;
  border-bottom-color: transparent;
}
.SPASample .nav-tabs.nav-justified {
  width: 100%;
  border-bottom: 0;
}
.SPASample .nav-tabs.nav-justified > li {
  float: none;
}
.SPASample .nav-tabs.nav-justified > li > a {
  margin-bottom: 5px;
  text-align: center;
}
.SPASample .nav-tabs.nav-justified > .dropdown .dropdown-menu {
  top: auto;
  left: auto;
}
@media (min-width: 768px) {
  .SPASample .nav-tabs.nav-justified > li {
    display: table-cell;
    width: 1%;
  }
  .SPASample .nav-tabs.nav-justified > li > a {
    margin-bottom: 0;
  }
}
.SPASample .nav-tabs.nav-justified > li > a {
  margin-right: 0;
  border-radius: 4px;
}
.SPASample .nav-tabs.nav-justified > .active > a,
.SPASample .nav-tabs.nav-justified > .active > a:hover,
.SPASample .nav-tabs.nav-justified > .active > a:focus {
  border: 1px solid #ddd;
}
@media (min-width: 768px) {
  .SPASample .nav-tabs.nav-justified > li > a {
    border-bottom: 1px solid #ddd;
    border-radius: 4px 4px 0 0;
  }
  .SPASample .nav-tabs.nav-justified > .active > a,
  .SPASample .nav-tabs.nav-justified > .active > a:hover,
  .SPASample .nav-tabs.nav-justified > .active > a:focus {
    border-bottom-color: #fff;
  }
}
.SPASample .nav-pills > li {
  float: left;
}
.SPASample .nav-pills > li > a {
  border-radius: 4px;
}
.SPASample .nav-pills > li + li {
  margin-left: 2px;
}
.SPASample .nav-pills > li.active > a,
.SPASample .nav-pills > li.active > a:hover,
.SPASample .nav-pills > li.active > a:focus {
  color: #fff;
  background-color: #337ab7;
}
.SPASample .nav-stacked > li {
  float: none;
}
.SPASample .nav-stacked > li + li {
  margin-top: 2px;
  margin-left: 0;
}
.SPASample .nav-justified {
  width: 100%;
}
.SPASample .nav-justified > li {
  float: none;
}
.SPASample .nav-justified > li > a {
  margin-bottom: 5px;
  text-align: center;
}
.SPASample .nav-justified > .dropdown .dropdown-menu {
  top: auto;
  left: auto;
}
@media (min-width: 768px) {
  .SPASample .nav-justified > li {
    display: table-cell;
    width: 1%;
  }
  .SPASample .nav-justified > li > a {
    margin-bottom: 0;
  }
}
.SPASample .nav-tabs-justified {
  border-bottom: 0;
}
.SPASample .nav-tabs-justified > li > a {
  margin-right: 0;
  border-radius: 4px;
}
.SPASample .nav-tabs-justified > .active > a,
.SPASample .nav-tabs-justified > .active > a:hover,
.SPASample .nav-tabs-justified > .active > a:focus {
  border: 1px solid #ddd;
}
@media (min-width: 768px) {
  .SPASample .nav-tabs-justified > li > a {
    border-bottom: 1px solid #ddd;
    border-radius: 4px 4px 0 0;
  }
  .SPASample .nav-tabs-justified > .active > a,
  .SPASample .nav-tabs-justified > .active > a:hover,
  .SPASample .nav-tabs-justified > .active > a:focus {
    border-bottom-color: #fff;
  }
}
.SPASample .tab-content > .tab-pane {
  display: none;
}
.SPASample .tab-content > .active {
  display: block;
}
.SPASample .nav-tabs .dropdown-menu {
  margin-top: -1px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.SPASample .navbar {
  position: relative;
  min-height: 50px;
  margin-bottom: 20px;
  border: 1px solid transparent;
}
@media (min-width: 768px) {
  .SPASample .navbar {
    border-radius: 4px;
  }
}
@media (min-width: 768px) {
  .SPASample .navbar-header {
    float: left;
  }
}
.SPASample .navbar-collapse {
  padding-right: 15px;
  padding-left: 15px;
  overflow-x: visible;
  -webkit-overflow-scrolling: touch;
  border-top: 1px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1);
}
.SPASample .navbar-collapse.in {
  overflow-y: auto;
}
@media (min-width: 768px) {
  .SPASample .navbar-collapse {
    width: auto;
    border-top: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
  .SPASample .navbar-collapse.collapse {
    display: block !important;
    height: auto !important;
    padding-bottom: 0;
    overflow: visible !important;
  }
  .SPASample .navbar-collapse.in {
    overflow-y: visible;
  }
  .SPASample .navbar-fixed-top .navbar-collapse,
  .SPASample .navbar-static-top .navbar-collapse,
  .SPASample .navbar-fixed-bottom .navbar-collapse {
    padding-right: 0;
    padding-left: 0;
  }
}
.SPASample .navbar-fixed-top .navbar-collapse,
.SPASample .navbar-fixed-bottom .navbar-collapse {
  max-height: 340px;
}
@media (max-device-width: 480px) and (orientation: landscape) {
  .SPASample .navbar-fixed-top .navbar-collapse,
  .SPASample .navbar-fixed-bottom .navbar-collapse {
    max-height: 200px;
  }
}
.SPASample .container > .navbar-header,
.SPASample .container-fluid > .navbar-header,
.SPASample .container > .navbar-collapse,
.SPASample .container-fluid > .navbar-collapse {
  margin-right: -15px;
  margin-left: -15px;
}
@media (min-width: 768px) {
  .SPASample .container > .navbar-header,
  .SPASample .container-fluid > .navbar-header,
  .SPASample .container > .navbar-collapse,
  .SPASample .container-fluid > .navbar-collapse {
    margin-right: 0;
    margin-left: 0;
  }
}
.SPASample .navbar-static-top {
  z-index: 1000;
  border-width: 0 0 1px;
}
@media (min-width: 768px) {
  .SPASample .navbar-static-top {
    border-radius: 0;
  }
}
.SPASample .navbar-fixed-top,
.SPASample .navbar-fixed-bottom {
  position: fixed;
  right: 0;
  left: 0;
  z-index: 1030;
}
@media (min-width: 768px) {
  .SPASample .navbar-fixed-top,
  .SPASample .navbar-fixed-bottom {
    border-radius: 0;
  }
}
.SPASample .navbar-fixed-top {
  top: 0;
  border-width: 0 0 1px;
}
.SPASample .navbar-fixed-bottom {
  bottom: 0;
  margin-bottom: 0;
  border-width: 1px 0 0;
}
.SPASample .navbar-brand {
  float: left;
  height: 50px;
  padding: 15px 15px;
  font-size: 18px;
  line-height: 20px;
}
.SPASample .navbar-brand:hover,
.SPASample .navbar-brand:focus {
  text-decoration: none;
}
.SPASample .navbar-brand > img {
  display: block;
}
@media (min-width: 768px) {
  .SPASample .navbar > .container .navbar-brand,
  .SPASample .navbar > .container-fluid .navbar-brand {
    margin-left: -15px;
  }
}
.SPASample .navbar-toggle {
  position: relative;
  float: right;
  padding: 9px 10px;
  margin-top: 8px;
  margin-right: 15px;
  margin-bottom: 8px;
  background-color: transparent;
  background-image: none;
  border: 1px solid transparent;
  border-radius: 4px;
}
.SPASample .navbar-toggle:focus {
  outline: 0;
}
.SPASample .navbar-toggle .icon-bar {
  display: block;
  width: 22px;
  height: 2px;
  border-radius: 1px;
}
.SPASample .navbar-toggle .icon-bar + .icon-bar {
  margin-top: 4px;
}
@media (min-width: 768px) {
  .SPASample .navbar-toggle {
    display: none;
  }
}
.SPASample .navbar-nav {
  margin: 7.5px -15px;
}
.SPASample .navbar-nav > li > a {
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 20px;
}
@media (max-width: 767px) {
  .SPASample .navbar-nav .open .dropdown-menu {
    position: static;
    float: none;
    width: auto;
    margin-top: 0;
    background-color: transparent;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
  .SPASample .navbar-nav .open .dropdown-menu > li > a,
  .SPASample .navbar-nav .open .dropdown-menu .dropdown-header {
    padding: 5px 15px 5px 25px;
  }
  .SPASample .navbar-nav .open .dropdown-menu > li > a {
    line-height: 20px;
  }
  .SPASample .navbar-nav .open .dropdown-menu > li > a:hover,
  .SPASample .navbar-nav .open .dropdown-menu > li > a:focus {
    background-image: none;
  }
}
@media (min-width: 768px) {
  .SPASample .navbar-nav {
    float: left;
    margin: 0;
  }
  .SPASample .navbar-nav > li {
    float: left;
  }
  .SPASample .navbar-nav > li > a {
    padding-top: 15px;
    padding-bottom: 15px;
  }
}
.SPASample .navbar-form {
  padding: 10px 15px;
  margin-top: 8px;
  margin-right: -15px;
  margin-bottom: 8px;
  margin-left: -15px;
  border-top: 1px solid transparent;
  border-bottom: 1px solid transparent;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.1);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.1);
}
@media (min-width: 768px) {
  .SPASample .navbar-form .form-group {
    display: inline-block;
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .navbar-form .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
  }
  .SPASample .navbar-form .form-control-static {
    display: inline-block;
  }
  .SPASample .navbar-form .input-group {
    display: inline-table;
    vertical-align: middle;
  }
  .SPASample .navbar-form .input-group .input-group-addon,
  .SPASample .navbar-form .input-group .input-group-btn,
  .SPASample .navbar-form .input-group .form-control {
    width: auto;
  }
  .SPASample .navbar-form .input-group > .form-control {
    width: 100%;
  }
  .SPASample .navbar-form .control-label {
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .navbar-form .radio,
  .SPASample .navbar-form .checkbox {
    display: inline-block;
    margin-top: 0;
    margin-bottom: 0;
    vertical-align: middle;
  }
  .SPASample .navbar-form .radio label,
  .SPASample .navbar-form .checkbox label {
    padding-left: 0;
  }
  .SPASample .navbar-form .radio input[type="radio"],
  .SPASample .navbar-form .checkbox input[type="checkbox"] {
    position: relative;
    margin-left: 0;
  }
  .SPASample .navbar-form .has-feedback .form-control-feedback {
    top: 0;
  }
}
@media (max-width: 767px) {
  .SPASample .navbar-form .form-group {
    margin-bottom: 5px;
  }
  .SPASample .navbar-form .form-group:last-child {
    margin-bottom: 0;
  }
}
@media (min-width: 768px) {
  .SPASample .navbar-form {
    width: auto;
    padding-top: 0;
    padding-bottom: 0;
    margin-right: 0;
    margin-left: 0;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
  }
}
.SPASample .navbar-nav > li > .dropdown-menu {
  margin-top: 0;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
.SPASample .navbar-fixed-bottom .navbar-nav > li > .dropdown-menu {
  margin-bottom: 0;
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.SPASample .navbar-btn {
  margin-top: 8px;
  margin-bottom: 8px;
}
.SPASample .navbar-btn.btn-sm {
  margin-top: 10px;
  margin-bottom: 10px;
}
.SPASample .navbar-btn.btn-xs {
  margin-top: 14px;
  margin-bottom: 14px;
}
.SPASample .navbar-text {
  margin-top: 15px;
  margin-bottom: 15px;
}
@media (min-width: 768px) {
  .SPASample .navbar-text {
    float: left;
    margin-right: 15px;
    margin-left: 15px;
  }
}
@media (min-width: 768px) {
  .SPASample .navbar-left {
    float: left !important;
  }
  .SPASample .navbar-right {
    float: right !important;
    margin-right: -15px;
  }
  .SPASample .navbar-right ~ .navbar-right {
    margin-right: 0;
  }
}
.SPASample .navbar-default {
  background-color: #f8f8f8;
  border-color: #e7e7e7;
}
.SPASample .navbar-default .navbar-brand {
  color: #777;
}
.SPASample .navbar-default .navbar-brand:hover,
.SPASample .navbar-default .navbar-brand:focus {
  color: #5e5e5e;
  background-color: transparent;
}
.SPASample .navbar-default .navbar-text {
  color: #777;
}
.SPASample .navbar-default .navbar-nav > li > a {
  color: #777;
}
.SPASample .navbar-default .navbar-nav > li > a:hover,
.SPASample .navbar-default .navbar-nav > li > a:focus {
  color: #333;
  background-color: transparent;
}
.SPASample .navbar-default .navbar-nav > .active > a,
.SPASample .navbar-default .navbar-nav > .active > a:hover,
.SPASample .navbar-default .navbar-nav > .active > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
.SPASample .navbar-default .navbar-nav > .disabled > a,
.SPASample .navbar-default .navbar-nav > .disabled > a:hover,
.SPASample .navbar-default .navbar-nav > .disabled > a:focus {
  color: #ccc;
  background-color: transparent;
}
.SPASample .navbar-default .navbar-toggle {
  border-color: #ddd;
}
.SPASample .navbar-default .navbar-toggle:hover,
.SPASample .navbar-default .navbar-toggle:focus {
  background-color: #ddd;
}
.SPASample .navbar-default .navbar-toggle .icon-bar {
  background-color: #888;
}
.SPASample .navbar-default .navbar-collapse,
.SPASample .navbar-default .navbar-form {
  border-color: #e7e7e7;
}
.SPASample .navbar-default .navbar-nav > .open > a,
.SPASample .navbar-default .navbar-nav > .open > a:hover,
.SPASample .navbar-default .navbar-nav > .open > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
@media (max-width: 767px) {
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > li > a {
    color: #777;
  }
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > li > a:hover,
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #333;
    background-color: transparent;
  }
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .active > a,
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .active > a:hover,
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #555;
    background-color: #e7e7e7;
  }
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a,
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a:hover,
  .SPASample .navbar-default .navbar-nav .open .dropdown-menu > .disabled > a:focus {
    color: #ccc;
    background-color: transparent;
  }
}
.SPASample .navbar-default .navbar-link {
  color: #777;
}
.SPASample .navbar-default .navbar-link:hover {
  color: #333;
}
.SPASample .navbar-default .btn-link {
  color: #777;
}
.SPASample .navbar-default .btn-link:hover,
.SPASample .navbar-default .btn-link:focus {
  color: #333;
}
.SPASample .navbar-default .btn-link[disabled]:hover,
.SPASample fieldset[disabled] .navbar-default .btn-link:hover,
.SPASample .navbar-default .btn-link[disabled]:focus,
.SPASample fieldset[disabled] .navbar-default .btn-link:focus {
  color: #ccc;
}
.SPASample .navbar-inverse {
  background-color: #222;
  border-color: #080808;
}
.SPASample .navbar-inverse .navbar-brand {
  color: #9d9d9d;
}
.SPASample .navbar-inverse .navbar-brand:hover,
.SPASample .navbar-inverse .navbar-brand:focus {
  color: #fff;
  background-color: transparent;
}
.SPASample .navbar-inverse .navbar-text {
  color: #9d9d9d;
}
.SPASample .navbar-inverse .navbar-nav > li > a {
  color: #9d9d9d;
}
.SPASample .navbar-inverse .navbar-nav > li > a:hover,
.SPASample .navbar-inverse .navbar-nav > li > a:focus {
  color: #fff;
  background-color: transparent;
}
.SPASample .navbar-inverse .navbar-nav > .active > a,
.SPASample .navbar-inverse .navbar-nav > .active > a:hover,
.SPASample .navbar-inverse .navbar-nav > .active > a:focus {
  color: #fff;
  background-color: #080808;
}
.SPASample .navbar-inverse .navbar-nav > .disabled > a,
.SPASample .navbar-inverse .navbar-nav > .disabled > a:hover,
.SPASample .navbar-inverse .navbar-nav > .disabled > a:focus {
  color: #444;
  background-color: transparent;
}
.SPASample .navbar-inverse .navbar-toggle {
  border-color: #333;
}
.SPASample .navbar-inverse .navbar-toggle:hover,
.SPASample .navbar-inverse .navbar-toggle:focus {
  background-color: #333;
}
.SPASample .navbar-inverse .navbar-toggle .icon-bar {
  background-color: #fff;
}
.SPASample .navbar-inverse .navbar-collapse,
.SPASample .navbar-inverse .navbar-form {
  border-color: #101010;
}
.SPASample .navbar-inverse .navbar-nav > .open > a,
.SPASample .navbar-inverse .navbar-nav > .open > a:hover,
.SPASample .navbar-inverse .navbar-nav > .open > a:focus {
  color: #fff;
  background-color: #080808;
}
@media (max-width: 767px) {
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .dropdown-header {
    border-color: #080808;
  }
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu .divider {
    background-color: #080808;
  }
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > li > a {
    color: #9d9d9d;
  }
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:hover,
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #fff;
    background-color: transparent;
  }
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a,
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:hover,
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #fff;
    background-color: #080808;
  }
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a,
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:hover,
  .SPASample .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:focus {
    color: #444;
    background-color: transparent;
  }
}
.SPASample .navbar-inverse .navbar-link {
  color: #9d9d9d;
}
.SPASample .navbar-inverse .navbar-link:hover {
  color: #fff;
}
.SPASample .navbar-inverse .btn-link {
  color: #9d9d9d;
}
.SPASample .navbar-inverse .btn-link:hover,
.SPASample .navbar-inverse .btn-link:focus {
  color: #fff;
}
.SPASample .navbar-inverse .btn-link[disabled]:hover,
.SPASample fieldset[disabled] .navbar-inverse .btn-link:hover,
.SPASample .navbar-inverse .btn-link[disabled]:focus,
.SPASample fieldset[disabled] .navbar-inverse .btn-link:focus {
  color: #444;
}
.SPASample .breadcrumb {
  padding: 8px 15px;
  margin-bottom: 20px;
  list-style: none;
  background-color: #f5f5f5;
  border-radius: 4px;
}
.SPASample .breadcrumb > li {
  display: inline-block;
}
.SPASample .breadcrumb > li + li:before {
  padding: 0 5px;
  color: #ccc;
  content: "/\00a0";
}
.SPASample .breadcrumb > .active {
  color: #777;
}
.SPASample .pagination {
  display: inline-block;
  padding-left: 0;
  margin: 20px 0;
  border-radius: 4px;
}
.SPASample .pagination > li {
  display: inline;
}
.SPASample .pagination > li > a,
.SPASample .pagination > li > span {
  position: relative;
  float: left;
  padding: 6px 12px;
  margin-left: -1px;
  line-height: 1.42857143;
  color: #337ab7;
  text-decoration: none;
  background-color: #fff;
  border: 1px solid #ddd;
}
.SPASample .pagination > li:first-child > a,
.SPASample .pagination > li:first-child > span {
  margin-left: 0;
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
}
.SPASample .pagination > li:last-child > a,
.SPASample .pagination > li:last-child > span {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}
.SPASample .pagination > li > a:hover,
.SPASample .pagination > li > span:hover,
.SPASample .pagination > li > a:focus,
.SPASample .pagination > li > span:focus {
  color: #23527c;
  background-color: #eee;
  border-color: #ddd;
}
.SPASample .pagination > .active > a,
.SPASample .pagination > .active > span,
.SPASample .pagination > .active > a:hover,
.SPASample .pagination > .active > span:hover,
.SPASample .pagination > .active > a:focus,
.SPASample .pagination > .active > span:focus {
  z-index: 2;
  color: #fff;
  cursor: default;
  background-color: #337ab7;
  border-color: #337ab7;
}
.SPASample .pagination > .disabled > span,
.SPASample .pagination > .disabled > span:hover,
.SPASample .pagination > .disabled > span:focus,
.SPASample .pagination > .disabled > a,
.SPASample .pagination > .disabled > a:hover,
.SPASample .pagination > .disabled > a:focus {
  color: #777;
  cursor: not-allowed;
  background-color: #fff;
  border-color: #ddd;
}
.SPASample .pagination-lg > li > a,
.SPASample .pagination-lg > li > span {
  padding: 10px 16px;
  font-size: 18px;
}
.SPASample .pagination-lg > li:first-child > a,
.SPASample .pagination-lg > li:first-child > span {
  border-top-left-radius: 6px;
  border-bottom-left-radius: 6px;
}
.SPASample .pagination-lg > li:last-child > a,
.SPASample .pagination-lg > li:last-child > span {
  border-top-right-radius: 6px;
  border-bottom-right-radius: 6px;
}
.SPASample .pagination-sm > li > a,
.SPASample .pagination-sm > li > span {
  padding: 5px 10px;
  font-size: 12px;
}
.SPASample .pagination-sm > li:first-child > a,
.SPASample .pagination-sm > li:first-child > span {
  border-top-left-radius: 3px;
  border-bottom-left-radius: 3px;
}
.SPASample .pagination-sm > li:last-child > a,
.SPASample .pagination-sm > li:last-child > span {
  border-top-right-radius: 3px;
  border-bottom-right-radius: 3px;
}
.SPASample .pager {
  padding-left: 0;
  margin: 20px 0;
  text-align: center;
  list-style: none;
}
.SPASample .pager li {
  display: inline;
}
.SPASample .pager li > a,
.SPASample .pager li > span {
  display: inline-block;
  padding: 5px 14px;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 15px;
}
.SPASample .pager li > a:hover,
.SPASample .pager li > a:focus {
  text-decoration: none;
  background-color: #eee;
}
.SPASample .pager .next > a,
.SPASample .pager .next > span {
  float: right;
}
.SPASample .pager .previous > a,
.SPASample .pager .previous > span {
  float: left;
}
.SPASample .pager .disabled > a,
.SPASample .pager .disabled > a:hover,
.SPASample .pager .disabled > a:focus,
.SPASample .pager .disabled > span {
  color: #777;
  cursor: not-allowed;
  background-color: #fff;
}
.SPASample .label {
  display: inline;
  padding: .2em .6em .3em;
  font-size: 75%;
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  border-radius: .25em;
}
.SPASample a.label:hover,
.SPASample a.label:focus {
  color: #fff;
  text-decoration: none;
  cursor: pointer;
}
.SPASample .label:empty {
  display: none;
}
.SPASample .btn .label {
  position: relative;
  top: -1px;
}
.SPASample .label-default {
  background-color: #777;
}
.SPASample .label-default[href]:hover,
.SPASample .label-default[href]:focus {
  background-color: #5e5e5e;
}
.SPASample .label-primary {
  background-color: #337ab7;
}
.SPASample .label-primary[href]:hover,
.SPASample .label-primary[href]:focus {
  background-color: #286090;
}
.SPASample .label-success {
  background-color: #5cb85c;
}
.SPASample .label-success[href]:hover,
.SPASample .label-success[href]:focus {
  background-color: #449d44;
}
.SPASample .label-info {
  background-color: #5bc0de;
}
.SPASample .label-info[href]:hover,
.SPASample .label-info[href]:focus {
  background-color: #31b0d5;
}
.SPASample .label-warning {
  background-color: #f0ad4e;
}
.SPASample .label-warning[href]:hover,
.SPASample .label-warning[href]:focus {
  background-color: #ec971f;
}
.SPASample .label-danger {
  background-color: #d9534f;
}
.SPASample .label-danger[href]:hover,
.SPASample .label-danger[href]:focus {
  background-color: #c9302c;
}
.SPASample .badge {
  display: inline-block;
  min-width: 10px;
  padding: 3px 7px;
  font-size: 12px;
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-align: center;
  white-space: nowrap;
  vertical-align: baseline;
  background-color: #777;
  border-radius: 10px;
}
.SPASample .badge:empty {
  display: none;
}
.SPASample .btn .badge {
  position: relative;
  top: -1px;
}
.SPASample .btn-xs .badge,
.SPASample .btn-group-xs > .btn .badge {
  top: 0;
  padding: 1px 5px;
}
.SPASample a.badge:hover,
.SPASample a.badge:focus {
  color: #fff;
  text-decoration: none;
  cursor: pointer;
}
.SPASample .list-group-item.active > .badge,
.SPASample .nav-pills > .active > a > .badge {
  color: #337ab7;
  background-color: #fff;
}
.SPASample .list-group-item > .badge {
  float: right;
}
.SPASample .list-group-item > .badge + .badge {
  margin-right: 5px;
}
.SPASample .nav-pills > li > a > .badge {
  margin-left: 3px;
}
.SPASample .jumbotron {
  padding: 30px 15px;
  margin-bottom: 30px;
  color: inherit;
  background-color: #eee;
}
.SPASample .jumbotron h1,
.SPASample .jumbotron .h1 {
  color: inherit;
}
.SPASample .jumbotron p {
  margin-bottom: 15px;
  font-size: 21px;
  font-weight: 200;
}
.SPASample .jumbotron > hr {
  border-top-color: #d5d5d5;
}
.SPASample .container .jumbotron,
.SPASample .container-fluid .jumbotron {
  border-radius: 6px;
}
.SPASample .jumbotron .container {
  max-width: 100%;
}
@media screen and (min-width: 768px) {
  .SPASample .jumbotron {
    padding: 48px 0;
  }
  .SPASample .container .jumbotron,
  .SPASample .container-fluid .jumbotron {
    padding-right: 60px;
    padding-left: 60px;
  }
  .SPASample .jumbotron h1,
  .SPASample .jumbotron .h1 {
    font-size: 63px;
  }
}
.SPASample .thumbnail {
  display: block;
  padding: 4px;
  margin-bottom: 20px;
  line-height: 1.42857143;
  background-color: #fff;
  border: 1px solid #ddd;
  border-radius: 4px;
  -webkit-transition: border 0.2s ease-in-out;
  -o-transition: border 0.2s ease-in-out;
  transition: border 0.2s ease-in-out;
}
.SPASample .thumbnail > img,
.SPASample .thumbnail a > img {
  margin-right: auto;
  margin-left: auto;
}
.SPASample a.thumbnail:hover,
.SPASample a.thumbnail:focus,
.SPASample a.thumbnail.active {
  border-color: #337ab7;
}
.SPASample .thumbnail .caption {
  padding: 9px;
  color: #333;
}
.SPASample .alert {
  padding: 15px;
  margin-bottom: 20px;
  border: 1px solid transparent;
  border-radius: 4px;
}
.SPASample .alert h4 {
  margin-top: 0;
  color: inherit;
}
.SPASample .alert .alert-link {
  font-weight: bold;
}
.SPASample .alert > p,
.SPASample .alert > ul {
  margin-bottom: 0;
}
.SPASample .alert > p + p {
  margin-top: 5px;
}
.SPASample .alert-dismissable,
.SPASample .alert-dismissible {
  padding-right: 35px;
}
.SPASample .alert-dismissable .close,
.SPASample .alert-dismissible .close {
  position: relative;
  top: -2px;
  right: -21px;
  color: inherit;
}
.SPASample .alert-success {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
.SPASample .alert-success hr {
  border-top-color: #c9e2b3;
}
.SPASample .alert-success .alert-link {
  color: #2b542c;
}
.SPASample .alert-info {
  color: #31708f;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
.SPASample .alert-info hr {
  border-top-color: #a6e1ec;
}
.SPASample .alert-info .alert-link {
  color: #245269;
}
.SPASample .alert-warning {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}
.SPASample .alert-warning hr {
  border-top-color: #f7e1b5;
}
.SPASample .alert-warning .alert-link {
  color: #66512c;
}
.SPASample .alert-danger {
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}
.SPASample .alert-danger hr {
  border-top-color: #e4b9c0;
}
.SPASample .alert-danger .alert-link {
  color: #843534;
}
@-webkit-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
@-o-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
@keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}
.SPASample .progress {
  height: 20px;
  margin-bottom: 20px;
  overflow: hidden;
  background-color: #f5f5f5;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}
.SPASample .progress-bar {
  float: left;
  width: 0;
  height: 100%;
  font-size: 12px;
  line-height: 20px;
  color: #fff;
  text-align: center;
  background-color: #337ab7;
  -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
  -webkit-transition: width .6s ease;
  -o-transition: width .6s ease;
  transition: width .6s ease;
}
.SPASample .progress-striped .progress-bar,
.SPASample .progress-bar-striped {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  -webkit-background-size: 40px 40px;
  background-size: 40px 40px;
}
.SPASample .progress.active .progress-bar,
.SPASample .progress-bar.active {
  -webkit-animation: progress-bar-stripes 2s linear infinite;
  -o-animation: progress-bar-stripes 2s linear infinite;
  animation: progress-bar-stripes 2s linear infinite;
}
.SPASample .progress-bar-success {
  background-color: #5cb85c;
}
.SPASample .progress-striped .progress-bar-success {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
.SPASample .progress-bar-info {
  background-color: #5bc0de;
}
.SPASample .progress-striped .progress-bar-info {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
.SPASample .progress-bar-warning {
  background-color: #f0ad4e;
}
.SPASample .progress-striped .progress-bar-warning {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
.SPASample .progress-bar-danger {
  background-color: #d9534f;
}
.SPASample .progress-striped .progress-bar-danger {
  background-image: -webkit-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}
.SPASample .media {
  margin-top: 15px;
}
.SPASample .media:first-child {
  margin-top: 0;
}
.SPASample .media,
.SPASample .media-body {
  overflow: hidden;
  zoom: 1;
}
.SPASample .media-body {
  width: 10000px;
}
.SPASample .media-object {
  display: block;
}
.SPASample .media-right,
.SPASample .media > .pull-right {
  padding-left: 10px;
}
.SPASample .media-left,
.SPASample .media > .pull-left {
  padding-right: 10px;
}
.SPASample .media-left,
.SPASample .media-right,
.SPASample .media-body {
  display: table-cell;
  vertical-align: top;
}
.SPASample .media-middle {
  vertical-align: middle;
}
.SPASample .media-bottom {
  vertical-align: bottom;
}
.SPASample .media-heading {
  margin-top: 0;
  margin-bottom: 5px;
}
.SPASample .media-list {
  padding-left: 0;
  list-style: none;
}
.SPASample .list-group {
  padding-left: 0;
  margin-bottom: 20px;
}
.SPASample .list-group-item {
  position: relative;
  display: block;
  padding: 10px 15px;
  margin-bottom: -1px;
  background-color: #fff;
  border: 1px solid #ddd;
}
.SPASample .list-group-item:first-child {
  border-top-left-radius: 4px;
  border-top-right-radius: 4px;
}
.SPASample .list-group-item:last-child {
  margin-bottom: 0;
  border-bottom-right-radius: 4px;
  border-bottom-left-radius: 4px;
}
.SPASample a.list-group-item {
  color: #555;
}
.SPASample a.list-group-item .list-group-item-heading {
  color: #333;
}
.SPASample a.list-group-item:hover,
.SPASample a.list-group-item:focus {
  color: #555;
  text-decoration: none;
  background-color: #f5f5f5;
}
.SPASample .list-group-item.disabled,
.SPASample .list-group-item.disabled:hover,
.SPASample .list-group-item.disabled:focus {
  color: #777;
  cursor: not-allowed;
  background-color: #eee;
}
.SPASample .list-group-item.disabled .list-group-item-heading,
.SPASample .list-group-item.disabled:hover .list-group-item-heading,
.SPASample .list-group-item.disabled:focus .list-group-item-heading {
  color: inherit;
}
.SPASample .list-group-item.disabled .list-group-item-text,
.SPASample .list-group-item.disabled:hover .list-group-item-text,
.SPASample .list-group-item.disabled:focus .list-group-item-text {
  color: #777;
}
.SPASample .list-group-item.active,
.SPASample .list-group-item.active:hover,
.SPASample .list-group-item.active:focus {
  z-index: 2;
  color: #fff;
  background-color: #337ab7;
  border-color: #337ab7;
}
.SPASample .list-group-item.active .list-group-item-heading,
.SPASample .list-group-item.active:hover .list-group-item-heading,
.SPASample .list-group-item.active:focus .list-group-item-heading,
.SPASample .list-group-item.active .list-group-item-heading > small,
.SPASample .list-group-item.active:hover .list-group-item-heading > small,
.SPASample .list-group-item.active:focus .list-group-item-heading > small,
.SPASample .list-group-item.active .list-group-item-heading > .small,
.SPASample .list-group-item.active:hover .list-group-item-heading > .small,
.SPASample .list-group-item.active:focus .list-group-item-heading > .small {
  color: inherit;
}
.SPASample .list-group-item.active .list-group-item-text,
.SPASample .list-group-item.active:hover .list-group-item-text,
.SPASample .list-group-item.active:focus .list-group-item-text {
  color: #c7ddef;
}
.SPASample .list-group-item-success {
  color: #3c763d;
  background-color: #dff0d8;
}
.SPASample a.list-group-item-success {
  color: #3c763d;
}
.SPASample a.list-group-item-success .list-group-item-heading {
  color: inherit;
}
.SPASample a.list-group-item-success:hover,
.SPASample a.list-group-item-success:focus {
  color: #3c763d;
  background-color: #d0e9c6;
}
.SPASample a.list-group-item-success.active,
.SPASample a.list-group-item-success.active:hover,
.SPASample a.list-group-item-success.active:focus {
  color: #fff;
  background-color: #3c763d;
  border-color: #3c763d;
}
.SPASample .list-group-item-info {
  color: #31708f;
  background-color: #d9edf7;
}
.SPASample a.list-group-item-info {
  color: #31708f;
}
.SPASample a.list-group-item-info .list-group-item-heading {
  color: inherit;
}
.SPASample a.list-group-item-info:hover,
.SPASample a.list-group-item-info:focus {
  color: #31708f;
  background-color: #c4e3f3;
}
.SPASample a.list-group-item-info.active,
.SPASample a.list-group-item-info.active:hover,
.SPASample a.list-group-item-info.active:focus {
  color: #fff;
  background-color: #31708f;
  border-color: #31708f;
}
.SPASample .list-group-item-warning {
  color: #8a6d3b;
  background-color: #fcf8e3;
}
.SPASample a.list-group-item-warning {
  color: #8a6d3b;
}
.SPASample a.list-group-item-warning .list-group-item-heading {
  color: inherit;
}
.SPASample a.list-group-item-warning:hover,
.SPASample a.list-group-item-warning:focus {
  color: #8a6d3b;
  background-color: #faf2cc;
}
.SPASample a.list-group-item-warning.active,
.SPASample a.list-group-item-warning.active:hover,
.SPASample a.list-group-item-warning.active:focus {
  color: #fff;
  background-color: #8a6d3b;
  border-color: #8a6d3b;
}
.SPASample .list-group-item-danger {
  color: #a94442;
  background-color: #f2dede;
}
.SPASample a.list-group-item-danger {
  color: #a94442;
}
.SPASample a.list-group-item-danger .list-group-item-heading {
  color: inherit;
}
.SPASample a.list-group-item-danger:hover,
.SPASample a.list-group-item-danger:focus {
  color: #a94442;
  background-color: #ebcccc;
}
.SPASample a.list-group-item-danger.active,
.SPASample a.list-group-item-danger.active:hover,
.SPASample a.list-group-item-danger.active:focus {
  color: #fff;
  background-color: #a94442;
  border-color: #a94442;
}
.SPASample .list-group-item-heading {
  margin-top: 0;
  margin-bottom: 5px;
}
.SPASample .list-group-item-text {
  margin-bottom: 0;
  line-height: 1.3;
}
.SPASample .panel {
  margin-bottom: 20px;
  background-color: #fff;
  border: 1px solid transparent;
  border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
}
.SPASample .panel-body {
  padding: 15px;
}
.SPASample .panel-heading {
  padding: 10px 15px;
  border-bottom: 1px solid transparent;
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
.SPASample .panel-heading > .dropdown .dropdown-toggle {
  color: inherit;
}
.SPASample .panel-title {
  margin-top: 0;
  margin-bottom: 0;
  font-size: 16px;
  color: inherit;
}
.SPASample .panel-title > a,
.SPASample .panel-title > small,
.SPASample .panel-title > .small,
.SPASample .panel-title > small > a,
.SPASample .panel-title > .small > a {
  color: inherit;
}
.SPASample .panel-footer {
  padding: 10px 15px;
  background-color: #f5f5f5;
  border-top: 1px solid #ddd;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
.SPASample .panel > .list-group,
.SPASample .panel > .panel-collapse > .list-group {
  margin-bottom: 0;
}
.SPASample .panel > .list-group .list-group-item,
.SPASample .panel > .panel-collapse > .list-group .list-group-item {
  border-width: 1px 0;
  border-radius: 0;
}
.SPASample .panel > .list-group:first-child .list-group-item:first-child,
.SPASample .panel > .panel-collapse > .list-group:first-child .list-group-item:first-child {
  border-top: 0;
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
.SPASample .panel > .list-group:last-child .list-group-item:last-child,
.SPASample .panel > .panel-collapse > .list-group:last-child .list-group-item:last-child {
  border-bottom: 0;
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
.SPASample .panel-heading + .list-group .list-group-item:first-child {
  border-top-width: 0;
}
.SPASample .list-group + .panel-footer {
  border-top-width: 0;
}
.SPASample .panel > .table,
.SPASample .panel > .table-responsive > .table,
.SPASample .panel > .panel-collapse > .table {
  margin-bottom: 0;
}
.SPASample .panel > .table caption,
.SPASample .panel > .table-responsive > .table caption,
.SPASample .panel > .panel-collapse > .table caption {
  padding-right: 15px;
  padding-left: 15px;
}
.SPASample .panel > .table:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child {
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
.SPASample .panel > .table:first-child > thead:first-child > tr:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child,
.SPASample .panel > .table:first-child > tbody:first-child > tr:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child {
  border-top-left-radius: 3px;
  border-top-right-radius: 3px;
}
.SPASample .panel > .table:first-child > thead:first-child > tr:first-child td:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child td:first-child,
.SPASample .panel > .table:first-child > tbody:first-child > tr:first-child td:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child td:first-child,
.SPASample .panel > .table:first-child > thead:first-child > tr:first-child th:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child th:first-child,
.SPASample .panel > .table:first-child > tbody:first-child > tr:first-child th:first-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child th:first-child {
  border-top-left-radius: 3px;
}
.SPASample .panel > .table:first-child > thead:first-child > tr:first-child td:last-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child td:last-child,
.SPASample .panel > .table:first-child > tbody:first-child > tr:first-child td:last-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child td:last-child,
.SPASample .panel > .table:first-child > thead:first-child > tr:first-child th:last-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > thead:first-child > tr:first-child th:last-child,
.SPASample .panel > .table:first-child > tbody:first-child > tr:first-child th:last-child,
.SPASample .panel > .table-responsive:first-child > .table:first-child > tbody:first-child > tr:first-child th:last-child {
  border-top-right-radius: 3px;
}
.SPASample .panel > .table:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child {
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
.SPASample .panel > .table:last-child > tbody:last-child > tr:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child,
.SPASample .panel > .table:last-child > tfoot:last-child > tr:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child {
  border-bottom-right-radius: 3px;
  border-bottom-left-radius: 3px;
}
.SPASample .panel > .table:last-child > tbody:last-child > tr:last-child td:first-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child td:first-child,
.SPASample .panel > .table:last-child > tfoot:last-child > tr:last-child td:first-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child td:first-child,
.SPASample .panel > .table:last-child > tbody:last-child > tr:last-child th:first-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child th:first-child,
.SPASample .panel > .table:last-child > tfoot:last-child > tr:last-child th:first-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child th:first-child {
  border-bottom-left-radius: 3px;
}
.SPASample .panel > .table:last-child > tbody:last-child > tr:last-child td:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child td:last-child,
.SPASample .panel > .table:last-child > tfoot:last-child > tr:last-child td:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child td:last-child,
.SPASample .panel > .table:last-child > tbody:last-child > tr:last-child th:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tbody:last-child > tr:last-child th:last-child,
.SPASample .panel > .table:last-child > tfoot:last-child > tr:last-child th:last-child,
.SPASample .panel > .table-responsive:last-child > .table:last-child > tfoot:last-child > tr:last-child th:last-child {
  border-bottom-right-radius: 3px;
}
.SPASample .panel > .panel-body + .table,
.SPASample .panel > .panel-body + .table-responsive,
.SPASample .panel > .table + .panel-body,
.SPASample .panel > .table-responsive + .panel-body {
  border-top: 1px solid #ddd;
}
.SPASample .panel > .table > tbody:first-child > tr:first-child th,
.SPASample .panel > .table > tbody:first-child > tr:first-child td {
  border-top: 0;
}
.SPASample .panel > .table-bordered,
.SPASample .panel > .table-responsive > .table-bordered {
  border: 0;
}
.SPASample .panel > .table-bordered > thead > tr > th:first-child,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr > th:first-child,
.SPASample .panel > .table-bordered > tbody > tr > th:first-child,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr > th:first-child,
.SPASample .panel > .table-bordered > tfoot > tr > th:first-child,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr > th:first-child,
.SPASample .panel > .table-bordered > thead > tr > td:first-child,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr > td:first-child,
.SPASample .panel > .table-bordered > tbody > tr > td:first-child,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr > td:first-child,
.SPASample .panel > .table-bordered > tfoot > tr > td:first-child,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr > td:first-child {
  border-left: 0;
}
.SPASample .panel > .table-bordered > thead > tr > th:last-child,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr > th:last-child,
.SPASample .panel > .table-bordered > tbody > tr > th:last-child,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr > th:last-child,
.SPASample .panel > .table-bordered > tfoot > tr > th:last-child,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr > th:last-child,
.SPASample .panel > .table-bordered > thead > tr > td:last-child,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr > td:last-child,
.SPASample .panel > .table-bordered > tbody > tr > td:last-child,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr > td:last-child,
.SPASample .panel > .table-bordered > tfoot > tr > td:last-child,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr > td:last-child {
  border-right: 0;
}
.SPASample .panel > .table-bordered > thead > tr:first-child > td,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr:first-child > td,
.SPASample .panel > .table-bordered > tbody > tr:first-child > td,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr:first-child > td,
.SPASample .panel > .table-bordered > thead > tr:first-child > th,
.SPASample .panel > .table-responsive > .table-bordered > thead > tr:first-child > th,
.SPASample .panel > .table-bordered > tbody > tr:first-child > th,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr:first-child > th {
  border-bottom: 0;
}
.SPASample .panel > .table-bordered > tbody > tr:last-child > td,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr:last-child > td,
.SPASample .panel > .table-bordered > tfoot > tr:last-child > td,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr:last-child > td,
.SPASample .panel > .table-bordered > tbody > tr:last-child > th,
.SPASample .panel > .table-responsive > .table-bordered > tbody > tr:last-child > th,
.SPASample .panel > .table-bordered > tfoot > tr:last-child > th,
.SPASample .panel > .table-responsive > .table-bordered > tfoot > tr:last-child > th {
  border-bottom: 0;
}
.SPASample .panel > .table-responsive {
  margin-bottom: 0;
  border: 0;
}
.SPASample .panel-group {
  margin-bottom: 20px;
}
.SPASample .panel-group .panel {
  margin-bottom: 0;
  border-radius: 4px;
}
.SPASample .panel-group .panel + .panel {
  margin-top: 5px;
}
.SPASample .panel-group .panel-heading {
  border-bottom: 0;
}
.SPASample .panel-group .panel-heading + .panel-collapse > .panel-body,
.SPASample .panel-group .panel-heading + .panel-collapse > .list-group {
  border-top: 1px solid #ddd;
}
.SPASample .panel-group .panel-footer {
  border-top: 0;
}
.SPASample .panel-group .panel-footer + .panel-collapse .panel-body {
  border-bottom: 1px solid #ddd;
}
.SPASample .panel-default {
  border-color: #ddd;
}
.SPASample .panel-default > .panel-heading {
  color: #333;
  background-color: #f5f5f5;
  border-color: #ddd;
}
.SPASample .panel-default > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #ddd;
}
.SPASample .panel-default > .panel-heading .badge {
  color: #f5f5f5;
  background-color: #333;
}
.SPASample .panel-default > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #ddd;
}
.SPASample .panel-primary {
  border-color: #337ab7;
}
.SPASample .panel-primary > .panel-heading {
  color: #fff;
  background-color: #337ab7;
  border-color: #337ab7;
}
.SPASample .panel-primary > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #337ab7;
}
.SPASample .panel-primary > .panel-heading .badge {
  color: #337ab7;
  background-color: #fff;
}
.SPASample .panel-primary > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #337ab7;
}
.SPASample .panel-success {
  border-color: #d6e9c6;
}
.SPASample .panel-success > .panel-heading {
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}
.SPASample .panel-success > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #d6e9c6;
}
.SPASample .panel-success > .panel-heading .badge {
  color: #dff0d8;
  background-color: #3c763d;
}
.SPASample .panel-success > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #d6e9c6;
}
.SPASample .panel-info {
  border-color: #bce8f1;
}
.SPASample .panel-info > .panel-heading {
  color: #31708f;
  background-color: #d9edf7;
  border-color: #bce8f1;
}
.SPASample .panel-info > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #bce8f1;
}
.SPASample .panel-info > .panel-heading .badge {
  color: #d9edf7;
  background-color: #31708f;
}
.SPASample .panel-info > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #bce8f1;
}
.SPASample .panel-warning {
  border-color: #faebcc;
}
.SPASample .panel-warning > .panel-heading {
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}
.SPASample .panel-warning > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #faebcc;
}
.SPASample .panel-warning > .panel-heading .badge {
  color: #fcf8e3;
  background-color: #8a6d3b;
}
.SPASample .panel-warning > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #faebcc;
}
.SPASample .panel-danger {
  border-color: #ebccd1;
}
.SPASample .panel-danger > .panel-heading {
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}
.SPASample .panel-danger > .panel-heading + .panel-collapse > .panel-body {
  border-top-color: #ebccd1;
}
.SPASample .panel-danger > .panel-heading .badge {
  color: #f2dede;
  background-color: #a94442;
}
.SPASample .panel-danger > .panel-footer + .panel-collapse > .panel-body {
  border-bottom-color: #ebccd1;
}
.SPASample .embed-responsive {
  position: relative;
  display: block;
  height: 0;
  padding: 0;
  overflow: hidden;
}
.SPASample .embed-responsive .embed-responsive-item,
.SPASample .embed-responsive iframe,
.SPASample .embed-responsive embed,
.SPASample .embed-responsive object,
.SPASample .embed-responsive video {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
.SPASample .embed-responsive-16by9 {
  padding-bottom: 56.25%;
}
.SPASample .embed-responsive-4by3 {
  padding-bottom: 75%;
}
.SPASample .well {
  min-height: 20px;
  padding: 19px;
  margin-bottom: 20px;
  background-color: #f5f5f5;
  border: 1px solid #e3e3e3;
  border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}
.SPASample .well blockquote {
  border-color: #ddd;
  border-color: rgba(0, 0, 0, 0.15);
}
.SPASample .well-lg {
  padding: 24px;
  border-radius: 6px;
}
.SPASample .well-sm {
  padding: 9px;
  border-radius: 3px;
}
.SPASample .close {
  float: right;
  font-size: 21px;
  font-weight: bold;
  line-height: 1;
  color: #000;
  text-shadow: 0 1px 0 #fff;
  filter: alpha(opacity=20);
  opacity: .2;
}
.SPASample .close:hover,
.SPASample .close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
  filter: alpha(opacity=50);
  opacity: .5;
}
.SPASample button.close {
  -webkit-appearance: none;
  padding: 0;
  cursor: pointer;
  background: transparent;
  border: 0;
}
.SPASample .modal-open {
  overflow: hidden;
}
.SPASample .modal {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1050;
  display: none;
  overflow: hidden;
  -webkit-overflow-scrolling: touch;
  outline: 0;
}
.SPASample .modal.fade .modal-dialog {
  -webkit-transition: -webkit-transform 0.3s ease-out;
  -o-transition: -o-transform 0.3s ease-out;
  transition: transform 0.3s ease-out;
  -webkit-transform: translate(0, -25%);
  -ms-transform: translate(0, -25%);
  -o-transform: translate(0, -25%);
  transform: translate(0, -25%);
}
.SPASample .modal.in .modal-dialog {
  -webkit-transform: translate(0, 0);
  -ms-transform: translate(0, 0);
  -o-transform: translate(0, 0);
  transform: translate(0, 0);
}
.SPASample .modal-open .modal {
  overflow-x: hidden;
  overflow-y: auto;
}
.SPASample .modal-dialog {
  position: relative;
  width: auto;
  margin: 10px;
}
.SPASample .modal-content {
  position: relative;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #999;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 6px;
  outline: 0;
  -webkit-box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
  box-shadow: 0 3px 9px rgba(0, 0, 0, 0.5);
}
.SPASample .modal-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  background-color: #000;
}
.SPASample .modal-backdrop.fade {
  filter: alpha(opacity=0);
  opacity: 0;
}
.SPASample .modal-backdrop.in {
  filter: alpha(opacity=50);
  opacity: .5;
}
.SPASample .modal-header {
  min-height: 16.42857143px;
  padding: 15px;
  border-bottom: 1px solid #e5e5e5;
}
.SPASample .modal-header .close {
  margin-top: -2px;
}
.SPASample .modal-title {
  margin: 0;
  line-height: 1.42857143;
}
.SPASample .modal-body {
  position: relative;
  padding: 15px;
}
.SPASample .modal-footer {
  padding: 15px;
  text-align: right;
  border-top: 1px solid #e5e5e5;
}
.SPASample .modal-footer .btn + .btn {
  margin-bottom: 0;
  margin-left: 5px;
}
.SPASample .modal-footer .btn-group .btn + .btn {
  margin-left: -1px;
}
.SPASample .modal-footer .btn-block + .btn-block {
  margin-left: 0;
}
.SPASample .modal-scrollbar-measure {
  position: absolute;
  top: -9999px;
  width: 50px;
  height: 50px;
  overflow: scroll;
}
@media (min-width: 768px) {
  .SPASample .modal-dialog {
    width: 600px;
    margin: 30px auto;
  }
  .SPASample .modal-content {
    -webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
  }
  .SPASample .modal-sm {
    width: 300px;
  }
}
@media (min-width: 992px) {
  .SPASample .modal-lg {
    width: 900px;
  }
}
.SPASample .tooltip {
  position: absolute;
  z-index: 1070;
  display: block;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 12px;
  font-weight: normal;
  line-height: 1.4;
  filter: alpha(opacity=0);
  opacity: 0;
}
.SPASample .tooltip.in {
  filter: alpha(opacity=90);
  opacity: .9;
}
.SPASample .tooltip.top {
  padding: 5px 0;
  margin-top: -3px;
}
.SPASample .tooltip.right {
  padding: 0 5px;
  margin-left: 3px;
}
.SPASample .tooltip.bottom {
  padding: 5px 0;
  margin-top: 3px;
}
.SPASample .tooltip.left {
  padding: 0 5px;
  margin-left: -3px;
}
.SPASample .tooltip-inner {
  max-width: 200px;
  padding: 3px 8px;
  color: #fff;
  text-align: center;
  text-decoration: none;
  background-color: #000;
  border-radius: 4px;
}
.SPASample .tooltip-arrow {
  position: absolute;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}
.SPASample .tooltip.top .tooltip-arrow {
  bottom: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
.SPASample .tooltip.top-left .tooltip-arrow {
  right: 5px;
  bottom: 0;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
.SPASample .tooltip.top-right .tooltip-arrow {
  bottom: 0;
  left: 5px;
  margin-bottom: -5px;
  border-width: 5px 5px 0;
  border-top-color: #000;
}
.SPASample .tooltip.right .tooltip-arrow {
  top: 50%;
  left: 0;
  margin-top: -5px;
  border-width: 5px 5px 5px 0;
  border-right-color: #000;
}
.SPASample .tooltip.left .tooltip-arrow {
  top: 50%;
  right: 0;
  margin-top: -5px;
  border-width: 5px 0 5px 5px;
  border-left-color: #000;
}
.SPASample .tooltip.bottom .tooltip-arrow {
  top: 0;
  left: 50%;
  margin-left: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
.SPASample .tooltip.bottom-left .tooltip-arrow {
  top: 0;
  right: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
.SPASample .tooltip.bottom-right .tooltip-arrow {
  top: 0;
  left: 5px;
  margin-top: -5px;
  border-width: 0 5px 5px;
  border-bottom-color: #000;
}
.SPASample .popover {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1060;
  display: none;
  max-width: 276px;
  padding: 1px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  font-weight: normal;
  line-height: 1.42857143;
  text-align: left;
  white-space: normal;
  background-color: #fff;
  -webkit-background-clip: padding-box;
  background-clip: padding-box;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  border-radius: 6px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
}
.SPASample .popover.top {
  margin-top: -10px;
}
.SPASample .popover.right {
  margin-left: 10px;
}
.SPASample .popover.bottom {
  margin-top: 10px;
}
.SPASample .popover.left {
  margin-left: -10px;
}
.SPASample .popover-title {
  padding: 8px 14px;
  margin: 0;
  font-size: 14px;
  background-color: #f7f7f7;
  border-bottom: 1px solid #ebebeb;
  border-radius: 5px 5px 0 0;
}
.SPASample .popover-content {
  padding: 9px 14px;
}
.SPASample .popover > .arrow,
.SPASample .popover > .arrow:after {
  position: absolute;
  display: block;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
}
.SPASample .popover > .arrow {
  border-width: 11px;
}
.SPASample .popover > .arrow:after {
  content: "";
  border-width: 10px;
}
.SPASample .popover.top > .arrow {
  bottom: -11px;
  left: 50%;
  margin-left: -11px;
  border-top-color: #999;
  border-top-color: rgba(0, 0, 0, 0.25);
  border-bottom-width: 0;
}
.SPASample .popover.top > .arrow:after {
  bottom: 1px;
  margin-left: -10px;
  content: " ";
  border-top-color: #fff;
  border-bottom-width: 0;
}
.SPASample .popover.right > .arrow {
  top: 50%;
  left: -11px;
  margin-top: -11px;
  border-right-color: #999;
  border-right-color: rgba(0, 0, 0, 0.25);
  border-left-width: 0;
}
.SPASample .popover.right > .arrow:after {
  bottom: -10px;
  left: 1px;
  content: " ";
  border-right-color: #fff;
  border-left-width: 0;
}
.SPASample .popover.bottom > .arrow {
  top: -11px;
  left: 50%;
  margin-left: -11px;
  border-top-width: 0;
  border-bottom-color: #999;
  border-bottom-color: rgba(0, 0, 0, 0.25);
}
.SPASample .popover.bottom > .arrow:after {
  top: 1px;
  margin-left: -10px;
  content: " ";
  border-top-width: 0;
  border-bottom-color: #fff;
}
.SPASample .popover.left > .arrow {
  top: 50%;
  right: -11px;
  margin-top: -11px;
  border-right-width: 0;
  border-left-color: #999;
  border-left-color: rgba(0, 0, 0, 0.25);
}
.SPASample .popover.left > .arrow:after {
  right: 1px;
  bottom: -10px;
  content: " ";
  border-right-width: 0;
  border-left-color: #fff;
}
.SPASample .carousel {
  position: relative;
}
.SPASample .carousel-inner {
  position: relative;
  width: 100%;
  overflow: hidden;
}
.SPASample .carousel-inner > .item {
  position: relative;
  display: none;
  -webkit-transition: 0.6s ease-in-out left;
  -o-transition: 0.6s ease-in-out left;
  transition: 0.6s ease-in-out left;
}
.SPASample .carousel-inner > .item > img,
.SPASample .carousel-inner > .item > a > img {
  line-height: 1;
}
@media all and (transform-3d), (-webkit-transform-3d) {
  .SPASample .carousel-inner > .item {
    -webkit-transition: -webkit-transform 0.6s ease-in-out;
    -o-transition: -o-transform 0.6s ease-in-out;
    transition: transform 0.6s ease-in-out;
    -webkit-backface-visibility: hidden;
    backface-visibility: hidden;
    -webkit-perspective: 1000;
    perspective: 1000;
  }
  .SPASample .carousel-inner > .item.next,
  .SPASample .carousel-inner > .item.active.right {
    left: 0;
    -webkit-transform: translate3d(100%, 0, 0);
    transform: translate3d(100%, 0, 0);
  }
  .SPASample .carousel-inner > .item.prev,
  .SPASample .carousel-inner > .item.active.left {
    left: 0;
    -webkit-transform: translate3d(-100%, 0, 0);
    transform: translate3d(-100%, 0, 0);
  }
  .SPASample .carousel-inner > .item.next.left,
  .SPASample .carousel-inner > .item.prev.right,
  .SPASample .carousel-inner > .item.active {
    left: 0;
    -webkit-transform: translate3d(0, 0, 0);
    transform: translate3d(0, 0, 0);
  }
}
.SPASample .carousel-inner > .active,
.SPASample .carousel-inner > .next,
.SPASample .carousel-inner > .prev {
  display: block;
}
.SPASample .carousel-inner > .active {
  left: 0;
}
.SPASample .carousel-inner > .next,
.SPASample .carousel-inner > .prev {
  position: absolute;
  top: 0;
  width: 100%;
}
.SPASample .carousel-inner > .next {
  left: 100%;
}
.SPASample .carousel-inner > .prev {
  left: -100%;
}
.SPASample .carousel-inner > .next.left,
.SPASample .carousel-inner > .prev.right {
  left: 0;
}
.SPASample .carousel-inner > .active.left {
  left: -100%;
}
.SPASample .carousel-inner > .active.right {
  left: 100%;
}
.SPASample .carousel-control {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 15%;
  font-size: 20px;
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.6);
  filter: alpha(opacity=50);
  opacity: .5;
}
.SPASample .carousel-control.left {
  background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  background-image: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0.5)), to(rgba(0, 0, 0, 0.0001)));
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#80000000', endColorstr='#00000000', GradientType=1);
  background-repeat: repeat-x;
}
.SPASample .carousel-control.right {
  right: 0;
  left: auto;
  background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  background-image: -o-linear-gradient(left, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  background-image: -webkit-gradient(linear, left top, right top, from(rgba(0, 0, 0, 0.0001)), to(rgba(0, 0, 0, 0.5)));
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#00000000', endColorstr='#80000000', GradientType=1);
  background-repeat: repeat-x;
}
.SPASample .carousel-control:hover,
.SPASample .carousel-control:focus {
  color: #fff;
  text-decoration: none;
  filter: alpha(opacity=90);
  outline: 0;
  opacity: .9;
}
.SPASample .carousel-control .icon-prev,
.SPASample .carousel-control .icon-next,
.SPASample .carousel-control .glyphicon-chevron-left,
.SPASample .carousel-control .glyphicon-chevron-right {
  position: absolute;
  top: 50%;
  z-index: 5;
  display: inline-block;
}
.SPASample .carousel-control .icon-prev,
.SPASample .carousel-control .glyphicon-chevron-left {
  left: 50%;
  margin-left: -10px;
}
.SPASample .carousel-control .icon-next,
.SPASample .carousel-control .glyphicon-chevron-right {
  right: 50%;
  margin-right: -10px;
}
.SPASample .carousel-control .icon-prev,
.SPASample .carousel-control .icon-next {
  width: 20px;
  height: 20px;
  margin-top: -10px;
  font-family: serif;
  line-height: 1;
}
.SPASample .carousel-control .icon-prev:before {
  content: '\2039';
}
.SPASample .carousel-control .icon-next:before {
  content: '\203a';
}
.SPASample .carousel-indicators {
  position: absolute;
  bottom: 10px;
  left: 50%;
  z-index: 15;
  width: 60%;
  padding-left: 0;
  margin-left: -30%;
  text-align: center;
  list-style: none;
}
.SPASample .carousel-indicators li {
  display: inline-block;
  width: 10px;
  height: 10px;
  margin: 1px;
  text-indent: -999px;
  cursor: pointer;
  background-color: #000 \9;
  background-color: rgba(0, 0, 0, 0);
  border: 1px solid #fff;
  border-radius: 10px;
}
.SPASample .carousel-indicators .active {
  width: 12px;
  height: 12px;
  margin: 0;
  background-color: #fff;
}
.SPASample .carousel-caption {
  position: absolute;
  right: 15%;
  bottom: 20px;
  left: 15%;
  z-index: 10;
  padding-top: 20px;
  padding-bottom: 20px;
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.6);
}
.SPASample .carousel-caption .btn {
  text-shadow: none;
}
@media screen and (min-width: 768px) {
  .SPASample .carousel-control .glyphicon-chevron-left,
  .SPASample .carousel-control .glyphicon-chevron-right,
  .SPASample .carousel-control .icon-prev,
  .SPASample .carousel-control .icon-next {
    width: 30px;
    height: 30px;
    margin-top: -15px;
    font-size: 30px;
  }
  .SPASample .carousel-control .glyphicon-chevron-left,
  .SPASample .carousel-control .icon-prev {
    margin-left: -15px;
  }
  .SPASample .carousel-control .glyphicon-chevron-right,
  .SPASample .carousel-control .icon-next {
    margin-right: -15px;
  }
  .SPASample .carousel-caption {
    right: 20%;
    left: 20%;
    padding-bottom: 30px;
  }
  .SPASample .carousel-indicators {
    bottom: 20px;
  }
}
.SPASample .clearfix:before,
.SPASample .clearfix:after,
.SPASample .dl-horizontal dd:before,
.SPASample .dl-horizontal dd:after,
.SPASample .container:before,
.SPASample .container:after,
.SPASample .container-fluid:before,
.SPASample .container-fluid:after,
.SPASample .row:before,
.SPASample .row:after,
.SPASample .form-horizontal .form-group:before,
.SPASample .form-horizontal .form-group:after,
.SPASample .btn-toolbar:before,
.SPASample .btn-toolbar:after,
.SPASample .btn-group-vertical > .btn-group:before,
.SPASample .btn-group-vertical > .btn-group:after,
.SPASample .nav:before,
.SPASample .nav:after,
.SPASample .navbar:before,
.SPASample .navbar:after,
.SPASample .navbar-header:before,
.SPASample .navbar-header:after,
.SPASample .navbar-collapse:before,
.SPASample .navbar-collapse:after,
.SPASample .pager:before,
.SPASample .pager:after,
.SPASample .panel-body:before,
.SPASample .panel-body:after,
.SPASample .modal-footer:before,
.SPASample .modal-footer:after {
  display: table;
  content: " ";
}
.SPASample .clearfix:after,
.SPASample .dl-horizontal dd:after,
.SPASample .container:after,
.SPASample .container-fluid:after,
.SPASample .row:after,
.SPASample .form-horizontal .form-group:after,
.SPASample .btn-toolbar:after,
.SPASample .btn-group-vertical > .btn-group:after,
.SPASample .nav:after,
.SPASample .navbar:after,
.SPASample .navbar-header:after,
.SPASample .navbar-collapse:after,
.SPASample .pager:after,
.SPASample .panel-body:after,
.SPASample .modal-footer:after {
  clear: both;
}
.SPASample .center-block {
  display: block;
  margin-right: auto;
  margin-left: auto;
}
.SPASample .pull-right {
  float: right !important;
}
.SPASample .pull-left {
  float: left !important;
}
.SPASample .hide {
  display: none !important;
}
.SPASample .show {
  display: block !important;
}
.SPASample .invisible {
  visibility: hidden;
}
.SPASample .text-hide {
  font: 0/0 a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}
.SPASample .hidden {
  display: none !important;
}
.SPASample .affix {
  position: fixed;
}
@-ms-viewport {
  width: device-width;
}
.SPASample .visible-xs,
.SPASample .visible-sm,
.SPASample .visible-md,
.SPASample .visible-lg {
  display: none !important;
}
.SPASample .visible-xs-block,
.SPASample .visible-xs-inline,
.SPASample .visible-xs-inline-block,
.SPASample .visible-sm-block,
.SPASample .visible-sm-inline,
.SPASample .visible-sm-inline-block,
.SPASample .visible-md-block,
.SPASample .visible-md-inline,
.SPASample .visible-md-inline-block,
.SPASample .visible-lg-block,
.SPASample .visible-lg-inline,
.SPASample .visible-lg-inline-block {
  display: none !important;
}
@media (max-width: 767px) {
  .SPASample .visible-xs {
    display: block !important;
  }
  .SPASample table.visible-xs {
    display: table;
  }
  .SPASample tr.visible-xs {
    display: table-row !important;
  }
  .SPASample th.visible-xs,
  .SPASample td.visible-xs {
    display: table-cell !important;
  }
}
@media (max-width: 767px) {
  .SPASample .visible-xs-block {
    display: block !important;
  }
}
@media (max-width: 767px) {
  .SPASample .visible-xs-inline {
    display: inline !important;
  }
}
@media (max-width: 767px) {
  .SPASample .visible-xs-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .SPASample .visible-sm {
    display: block !important;
  }
  .SPASample table.visible-sm {
    display: table;
  }
  .SPASample tr.visible-sm {
    display: table-row !important;
  }
  .SPASample th.visible-sm,
  .SPASample td.visible-sm {
    display: table-cell !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .SPASample .visible-sm-block {
    display: block !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .SPASample .visible-sm-inline {
    display: inline !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .SPASample .visible-sm-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  .SPASample .visible-md {
    display: block !important;
  }
  .SPASample table.visible-md {
    display: table;
  }
  .SPASample tr.visible-md {
    display: table-row !important;
  }
  .SPASample th.visible-md,
  .SPASample td.visible-md {
    display: table-cell !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  .SPASample .visible-md-block {
    display: block !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  .SPASample .visible-md-inline {
    display: inline !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  .SPASample .visible-md-inline-block {
    display: inline-block !important;
  }
}
@media (min-width: 1200px) {
  .SPASample .visible-lg {
    display: block !important;
  }
  .SPASample table.visible-lg {
    display: table;
  }
  .SPASample tr.visible-lg {
    display: table-row !important;
  }
  .SPASample th.visible-lg,
  .SPASample td.visible-lg {
    display: table-cell !important;
  }
}
@media (min-width: 1200px) {
  .SPASample .visible-lg-block {
    display: block !important;
  }
}
@media (min-width: 1200px) {
  .SPASample .visible-lg-inline {
    display: inline !important;
  }
}
@media (min-width: 1200px) {
  .SPASample .visible-lg-inline-block {
    display: inline-block !important;
  }
}
@media (max-width: 767px) {
  .SPASample .hidden-xs {
    display: none !important;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .SPASample .hidden-sm {
    display: none !important;
  }
}
@media (min-width: 992px) and (max-width: 1199px) {
  .SPASample .hidden-md {
    display: none !important;
  }
}
@media (min-width: 1200px) {
  .SPASample .hidden-lg {
    display: none !important;
  }
}
.SPASample .visible-print {
  display: none !important;
}
@media print {
  .SPASample .visible-print {
    display: block !important;
  }
  .SPASample table.visible-print {
    display: table;
  }
  .SPASample tr.visible-print {
    display: table-row !important;
  }
  .SPASample th.visible-print,
  .SPASample td.visible-print {
    display: table-cell !important;
  }
}
.SPASample .visible-print-block {
  display: none !important;
}
@media print {
  .SPASample .visible-print-block {
    display: block !important;
  }
}
.SPASample .visible-print-inline {
  display: none !important;
}
@media print {
  .SPASample .visible-print-inline {
    display: inline !important;
  }
}
.SPASample .visible-print-inline-block {
  display: none !important;
}
@media print {
  .SPASample .visible-print-inline-block {
    display: inline-block !important;
  }
}
@media print {
  .SPASample .hidden-print {
    display: none !important;
  }
}